### ISSUE TITLE
Feature Request: message actions

### ISSUE THREAD

**Issue by sug0mi** [rigormorrtiss/discordo#109]
It would be nice if there was a way to edit and delete messages. Also, it would be really cool if we selected an image and hit enter, the default image viewer would open, and if you selected a link, the default browser would open.

**Comment by ghost** [comment]
Sorry for the delayed response. I plan to implement a context menu for message actions eventually. Unfortunately, the [context menus pull-request](https://github.com/rivo/tview/pull/434) is not merged in `tview` yet.
