### ISSUE TITLE
Messages From All Guilds Delivered In All Channels

### ISSUE THREAD

**Issue by hobby-grade** [rigormorrtiss/discordo#119]
When I load a direct message or a channel, all messages from all channels in all servers that I am in are delivered at all times.

**Comment by ghost** [comment]
I cannot seem to reproduce this, even when a direct messages is loaded; can you provide reproducible steps?

EDIT: This bug is fixed by #120

**Comment by hobby-grade** [comment]
Works great now, thanks for the quick fix!
