### ISSUE TITLE
 Feature request: Dunst integration

### ISSUE THREAD

**Issue by Spuxy** [rigormorrtiss/discordo#121]
It would be good to provide notification syscalls like original discord does. 
I can make PR for that. But idk if u want to approve it, because of another dependency.

I would like to add the most used notification library "dunst".

**Comment by ghost** [comment]
Discordo previously had desktop notifications feature using a cross-platform desktop notifications library ― [beeep](https://github.com/gen2brain/beeep). During major code refactor, I temporarily removed desktop notifications configuration as well as the feature; however, I plan to eventually add desktop notifications feature back. How does dunst differ from beeep? I am not really against adding another dependency.

EDIT: looks like dunst is not cross-platform.

**Comment by Spuxy** [comment]
ah sorry i was out of pc. Anyway i guess dunst is overall more popular in unix community for ricing and its more customizable. And yes dunst is for linux only but i can implement another notification library. For that, i can work on beeep implementation. I would like to help u and i would do that clean as possible.
