### ISSUE TITLE
Is there a help menu for keybindings?

### ISSUE THREAD

**Issue by molleweide** [rigormorrtiss/discordo#124]
Hi again ayntgl!

Again I really appreciate your work - I am learning go atm so maybe I'll be able to help out in the future.

I want to ask if there will be a legend for showing keybinds in the works. Currently I am not understanding what
keybindigs can be used. Maybe I just haven't looked around thourougly enough in the project.

Cheers,

**Comment by ghost** [comment]
Hey @molleweide! A default configuration file is created at `$HOME/.config/discordo/config.toml` on Unix, `$HOME/Library/Application Support/discordo/config.toml` on Darwin, and `%AppData%/discordo/config.toml` on Windows; you can find the corresponding keybinding for each action in form of key-value pair in the configuration file. The configuration file uses the [TOML file format](https://github.com/toml-lang/toml) for easy-to-read configuration. Currently, there is no help menu builtin to the application. This may change in future.

**Comment by molleweide** [comment]
nice, I see now that the keybindings are listed in the config file. Thanks man!
