### ISSUE TITLE
Prebuilt Binary for Linux error

### ISSUE THREAD

**Issue by IdleEndeavor** [rigormorrtiss/discordo#125]
Hello there

I needed some help with running the prebuilt binary on Pop OS.
I extracted the downloaded zip and gave the file inside permission to run as an executable. But running it does nothing.

Kindly help me with this issue. Thanks!

**Comment by ghost** [comment]
Hey @IdleEndeavor, can you elaborate and explain what you mean by "running it does nothing"? Furthermore, can you also mention additional details such as operating system version and the desktop environment or window manager that you are running. I am not able to reproduce this issue, it would be extremely helpful if you can provide step-by-step reproducible steps.

**Comment by IdleEndeavor** [comment]
16 GB RAM
Intel® Core™ i5-8265U CPU @ 1.60GHz × 8
NVIDIA Corporation GM108M [GeForce MX110]
Pop!_OS 21.10
X11

I gave the extracted file named *discordo* permission to run as an executable, However, it doesn't open any windows in the background or foreground. Nothing happens at all.

It may be a mistake on my part in not knowing how to run the file. In that case, I am extremely sorry, but please do guide me. Thank you

**Comment by ghost** [comment]
You will have to also [run the executable with no arguments](https://github.com/ayntgl/discordo#usage) in a new Terminal window:

```bash
unzip ./discordo_Linux_X64.zip
chmod +x ./discordo_Linux_X64
./discordo_Linux_X64

# optional
sudo mv ./discordo_Linux_X64 /usr/local/bin/discordo
```

**Comment by IdleEndeavor** [comment]
Hey dev

Kindly mention these exact steps in the ReadMe
otherwise dumb guys like me will mess it up

Sorry for the inconvenience
