### ISSUE TITLE
Crashes on wrongpass

### ISSUE THREAD

**Issue by GameKyuubi** [rigormorrtiss/discordo#127]
Tho it works fine when the pass is fine, if you get the pass wrong the app will crash.

**Comment by ghost** [comment]
Discordo uses platform-specific keyring to store the client authentication token ― GNOME Keyring for Linux, Keychain for macOS (builtin), and Windows Credential Manager for Windows (builtin); if the implementation is not found on the device, it uses email and password to log in instead. Furthermore, if a wrong password is entered in the password field... the application exits and panic is thrown. This is the intended behavior.
