### ISSUE TITLE
Feature request: chat history (scrollbar)

### ISSUE THREAD

**Issue by krisdyb** [rigormorrtiss/discordo#128]
Current version shows only one full screen of chat history without the possibility to scroll upwards for more

**Comment by ghost** [comment]
You can set `timestamps` field in the configuration file to `true` to render timestamps beside the name of the author of a message. Here's a preview:
![image](https://user-images.githubusercontent.com/90600421/155517130-e9c95428-8405-4ab2-a668-2394b2e37e4a.png)

**Comment by krisdyb** [comment]
Thank you @ayntgl 
I realized this after I created the request and have now updated the request to only cover extended chat history.

**Comment by krisdyb** [comment]
Escape-escape then the hotkeys are working, except for the actions Rune[a] list

**Comment by ghost** [comment]
Regarding chat history, you can scroll through the chat history using the mouse-wheel or the arrow up and arrow down keys; however, only 50 channel messages are loaded by default, this can be changed using the configuration file (see `fetch_messages_limit` field in the configuration file). You can set the default fetch messages limit to a greater natural number, remember that the maximum fetch messages limit is 100 (which is enforced by Discord API).

Additionally, [tview](https://github.com/rivo/tview) does not have support for scrollbars yet. There is an [open pull request that implements support for scrollbars](https://github.com/rivo/tview/pull/396) for a lot of UI widgets, but unfortunately, the `TextView` widget is not one of them.

Moreover, the keyboard shortcut `Rune[a]` is to display message actions list that contains additional actions for the selected message, it is a widget-specific keybinding (only works when the `TextView` widget is focused). Also, a message must be selected to display it, you can select messages by focusing on the `TextView` widget and using the arrow keys to select a message or click on a message to select it.
