### ISSUE TITLE
Transparency Issue

### ISSUE THREAD

**Issue by tildethine** [rigormorrtiss/discordo#133]
I'm using i3 with Kitty as my terminal. I have made my terminal transparent but whenever I launch Discordo it doesn't follow the assigned transparency.

https://i.imgur.com/AtoVWPf.png

I have looked into a past issue about transparency https://github.com/ayntgl/discordo/issues/63 but it doesn't seem to be working for me. 

I added "ColorDefault = 0" into /home/user/discordo/config.toml but it remained the same.

**Comment by ghost** [comment]
> I added "ColorDefault = 0" into /home/user/discordo/config.toml but it remained the same.

The `Theme` field had been removed from the configuration file, temporarily.

**Comment by ghost** [comment]
@tildethine, you can now set the `theme.background` field to an empty string in the configuration file to have a transparent background.

**Comment by tildethine** [comment]
Is my TOML file supposed to be looking like this?
[theme]
  border = "white"
  title = "white"
  background = "" 

Because it's still black for some reason.
