### ISSUE TITLE
Crashes everytime

### ISSUE THREAD

**Issue by alqix0** [rigormorrtiss/discordo#135]

**Comment by ghost** [comment]
Could you provide more details?

**Comment by alqix0** [comment]
Yeah. When I click on specific server. It crashes immediately. Sometimes crashes for no reason.

**Comment by alqix0** [comment]
@ayntgl It's only happening with newly added servers.

**Comment by ghost** [comment]
I am not able to reproduce this issue, please provide reproducible steps.
