### ISSUE TITLE
I'm confused in how to add transperency.

### ISSUE THREAD

**Issue by tildethine** [rigormorrtiss/discordo#151]
I'm using kitty terminal. and my terminal already has transparency.
I have submitted an issue about it here 'https://github.com/ayntgl/discordo/issues/133'
But I'm not sure how to implement the solution. I setted up my TOML file to look like this
[theme]
border = "white"
title = "white"
background = ""

I was following instructions from this comment "@tildethine, you can now set the theme.background field to an empty string in the configuration file to have a transparent background." submitted by @ayntgl   

But after doing that my discordo is still not transparent :/ I've looked into `theme.go` and this is what I see. 
package config

type ThemeConfig struct {
	Background string `toml:"background"`
	Border     string `toml:"border"`
	Title      string `toml:"title"`
}

func newThemeConfig() ThemeConfig {
	return ThemeConfig{
		Background: "",
		Border:     "white",
		Title:      "white",
	}
}

Looks like it read the TOML file but it's still not transparent :/

**Comment by ghost** [comment]
Can you try setting `background_opacity` to `0` (fully transparent) in `~/.config/kitty/kitty.conf`?

**Comment by tildethine** [comment]
@ayntgl  This is what I get https://i.imgur.com/v0VaCQw.png

**Comment by ghost** [comment]
@tildethine, do you mind dumping contents of `~/.config/kitty/kitty.conf` here? Unfortunately, I am unable to reproduce this issue.

![image](https://user-images.githubusercontent.com/90600421/160101968-c1bdff29-de3c-4c2d-b498-03c4a9c0eabe.png)

**Comment by tildethine** [comment]
Sure,

cursor                  #928374
cursor_text_color       background

url_color               #83a598

visual_bell_color       #8ec07c
bell_border_color       #8ec07c

active_border_color     #d3869b
inactive_border_color   #665c54

background              #282828
foreground              #fbf1c7
selection_foreground    #928374
selection_background    #ebdbb2

active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836

#black
color0                  #282828
color8                  #7c6f64

#red
color1                  #cc241d
color9                  #fb4934

#green
color2                  #98971a
color10                 #b8bb26

#yellow
color3                  #d79921
color11                 #fabd2f

#blue
color4                  #458588
color12                 #83a598

#purple
color5                  #b16286
color13                 #d3869b

#aqua
color6                  #689d6a
color14                 #8ec07c

#white
color7                  #a89984
color15                 #fbf1c7

#transparency
background_opacity 0


On the other hand, may I have your kitty.conf? I would like to try using it to see if it works

INFO: I tried launching kitty with an empty config file which defaults it to pure black, and after launching discordo, the background is pure black as well. But after setting background_opacity in kitty.conf discordo still stays pure black

UPDATE: Deleted discordo and performing a reinstall

**Comment by ayntgl** [comment]
am using your Kitty configuration file with `theme.background` as an empty string (in `~/.config/discordo/config.toml`) and it seems to work just fine for me.

```toml
...
[theme]
  background = ""
  border = "white"
  title = "white"
...
```

**Comment by tildethine** [comment]
@ayntgl I think I know what's wrong but I need help. So from my last issue in #133 , I thought I had deleted discordo and reinstalled to make use of the newly added `theme.background`. Because I only just realized that the TOML file takes any value and requires an input. For example I could add `poop =`  in config.toml and I get this error after running discordo 

`line 17 (last key "theme.poop"): expected value but found '\n' instead`

So I guess you can see where this is going, I tried it for background first and I got that error so I assumed it's already updated to have theme.background in the code....

This is where I'm stuck at. I can't completely delete discordo. Even after manually deleting the files and running git clone all over again this is what I get after running `make build` 

:~/discordo$ make build
go build \
	-trimpath \
	-buildmode=pie \
	-ldflags "-s -w" \

It ends there and I can launch discordo again. It doesn't install or compile anything. I'm not sure what to do from here...

INFO: Is it possible to have an apt package? For easy updates and install in Ubuntu.

**Comment by ghost** [comment]
@tildethine, after you have built the executable using `make build`, you need to execute it; you can do so by running `./discordo` (`./` refers to the [current directory](https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths); `make build` creates an executable in your current directory) command.

> INFO: Is it possible to have an apt package? For easy updates and install in Ubuntu.

If you are on Arch Linux, you can install Discordo from the AUR ([`discordo-git`](https://aur.archlinux.org/packages/discordo-git)) manually (`makepkg -si`) or using an AUR helper (`paru -S discordo-git`). Unfortunately, I am not familiar with the Ubuntu package release procedure. If someone with enough knowledge wants to assist me, I am more than happy to release it to the Ubuntu repositories. Additionally, the CI/workflow automatically uploads the built binary as an artifact, you may download it from there (you can find the links in the README) and add the location of the binary to your `PATH` variable or move it to `/usr/local/bin` directory.

**Comment by ayntgl** [comment]
@tildethine, if you are on Arch Linux, you can install Discordo from the AUR ([`discordo-git`](https://aur.archlinux.org/packages/discordo-git)) manually (`makepkg -si`) or using an AUR helper (`paru -S discordo-git`). Unfortunately, I am not familiar with the Ubuntu package release procedure. If someone with enough knowledge wants to help me out, I am more than happy to add it to the Ubuntu repositories.

**Comment by Spuxy** [comment]
i need to agree that transparency does not work at all :( could u please provide quick tutorial how to do it into README.md ? I guess many ppl would avoid to being confused 👯
