### ISSUE TITLE
Unread channels not showing

### ISSUE THREAD

**Issue by Hate9** [rigormorrtiss/discordo#159]
![image](https://user-images.githubusercontent.com/4684153/173469853-1683c15f-82ba-4f32-95f2-7f17910adcc9.png)![image](https://user-images.githubusercontent.com/4684153/173469940-6a9ea5f7-783e-4322-94cd-65a283acc346.png)
As you can see from the from the above screenshots, discordo doesn't appear to show the unread status of channels or servers. As this appears to work in the screenshot in the readme, I assume this should be considered a bug report, and not a feature request.

**Comment by ghost** [comment]
HI there, I am not able to reproduce this issue, could you provide the reproducible steps so I can look into it?

**Comment by Hate9** [comment]
I… installed the application from the AUR, and launched it with my token? those are the only steps I took.
