### ISSUE TITLE
Feature request: Delete messages

### ISSUE THREAD

**Issue by Chirunos** [rigormorrtiss/discordo#163]
I wish I could somehow delete highlighted messages

**Comment by Chirunos** [comment]
Doesn't work :(
It should be "d" or "Delete" do delete the messages right?

**Comment by ghost** [comment]
> Doesn't work :( It should be "d" or "Delete" do delete the messages right?

Yes. Note that if the "Delete" action is not present in the messages actions list, it means that you do not have sufficient permission to delete the currently-selected message.

**Comment by ghost** [comment]
> Doesn't work :( It should be "d" or "Delete" do delete the messages right?

Furthermore, you will have to first open the messages action list to delete the message; you can open it using the key "a". Lastly, hit "d" after you have opened the messages action list to delete the message.

**Comment by Chirunos** [comment]
I'm sorry, I didn't knew about the action list 🙃
