### ISSUE TITLE
Nothing happens after pressing "LOGIN" button.

### ISSUE THREAD

**Issue by Hexzatite** [rigormorrtiss/discordo#165]
Title is what it says. Even if I put in a knowingly fake email and password, nothing happens when I try and press the login button. It hangs for a split second, then does nothing. No errors that I can visually see however.
Would be helpful if I knew the location of some sort of log file or something of the sort, but I can't find any, apologies for that.

OS: Arch 5.18.12-arch1-1 (Archcraft)
Terminal: Alacritty 0.10.1-2
Discordo: r119.797d557-1 (Version currently on the AUR)

**Comment by gohoski** [comment]
You can try logging in using a token. This is probably the only way that is working

**Comment by Hexzatite** [comment]
> You can try logging in using a token. This is probably the only way that is working

I could try, How would I go about doing that? Getting the token off the web version and then passing it to discordo?

**Comment by ghost** [comment]
@Ahndrek-LiCyri, thanks for the bug report, I will look into this issue.

> I could try, How would I go about doing that? Getting the token off the web version and then passing it to discordo?

You can login using the client authentication token by supplying it to the `token` flag. Eg: `discordo --token "TOKEN HERE"`

**Comment by hajosattila** [comment]
Same problem here...

Arch 5.18.14-arch1-1
Sway 1.7
Alacritty 0.10.1
Discordo r447.205c9da-1

discordo --token "TOKEN HERE" working fine, but if I put the token in config.json, it doesn't work.

Sorry for my bad English

**Comment by ghost** [comment]
Discord sends an email to verify login if the user has logged in from a new location; go to your mail inbox and verify the login request to continue.

**Comment by hajosattila** [comment]
> Discord sends an email to verify login if the user has logged in from a new location; go to your mail inbox and verify the login request to continue.

I have not received an e-mail.

**Comment by markaudacity** [comment]
Same issue here.
