### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by umop3plsdn** [rigormorrtiss/discordo#168]
When I try to login it literally does nothing no feedback at all. Just have the email password and login button

**Comment by gohoski** [comment]
Try logging in using a token.

**Comment by umop3plsdn** [comment]
i tried the token route but everything is just blank https://imgur.com/F9ZTvsOl.png

**Comment by umop3plsdn** [comment]
uhh nevermind the token works I had tried by using the prefix Bot before like the documentation said
