### ISSUE TITLE
shortcut keys

### ISSUE THREAD

**Issue by umop3plsdn** [rigormorrtiss/discordo#169]
after opening a channel is there a keyboard shortcut to get back to the parent list without having to use the mouse?

**Comment by umop3plsdn** [comment]
Found them in the config.. anyone else wanting to know this info:
   toggle_guilds_list = "Rune[g]"
   toggle_channels_tree_view = "Rune[c]"
   toggle_messages_text_view = "Rune[m]"
   toggle_message_input_field = "Rune[i]"
   open_message_actions_list = "Rune[a]"
   open_external_editor = "Ctrl+E"
   select_previous_message = "Up"
   select_next_message = "Down"
   select_first_message = "Home"
   select_last_message = "End"

**Comment by slashdottir** [comment]
Any idea what a "Rune" is? is it some kind of Go thing?

**Comment by ghost** [comment]
> after opening a channel is there a keyboard shortcut to get back to the parent list without having to use the mouse?

Yes, you are right. The Go language defines the word `rune` as an alias for the type `int32`, so programs can be clear when an integer value represents a code point. For characters (though there is distinction between a character and rune), you have to wrap them in `Rune[x]`, where `x` is any character.
