### ISSUE TITLE
Feature request: download entire channel to text file

### ISSUE THREAD

**Issue by slashdottir** [rigormorrtiss/discordo#173]
with the ability to jump to the first message in a channel.

**Comment by simbafs** [comment]
want it

**Comment by ghost** [comment]
> with the ability to jump to the first message in a channel.

Hello there, @slashdottir! You can jump to the first message (within the messages limit) using the `Home` key which can be changed in the configuration file.

**Comment by slashdottir** [comment]
What about downloading the entire channel to text file?  Thank you for any info

**Comment by slashdottir** [comment]
I understand now that the maximum message limit is 100, so for big channels, no way to jump to the first ever message.

I would still love it if there was a way to download the entire channel.  Maybe I will learn go and try to figure this out!  😝

**Comment by peepo5** [comment]
It would be more ideal as a json file. top level data could have channel name, description, perms, id. messages data would be an array of hashmaps including who sent the msg, message content, post time, reactions etc.
