### ISSUE TITLE
Feature request: Add support for guild folders

### ISSUE THREAD

**Issue by Eroxl** [rigormorrtiss/discordo#174]
### Reasoning
Navigating guilds right now if you have a lot of them can be annoying it would be really nice to be able to have a feature to support guild folders like the normal discord app.

Not sure if this is possible but it would be a really nice feature to have.

**Comment by Arian-D** [comment]
I'm not familiar with Discord's API, but is there a way to also retrieve the folder name? My folders show up as just `Folder`
![image](https://user-images.githubusercontent.com/40076285/212525993-5248bb43-126b-4f0b-bcbb-29fe516b62c0.png)
whereas the native client can show the names and their unique color.
![image](https://user-images.githubusercontent.com/40076285/212526087-39fab905-e9a9-4485-93e7-94d226ae047a.png)

**Comment by Eroxl** [comment]
@Arian-D It might be a bug for you; they show up with the correct name and colour for me.
<img width="302" alt="Screen Shot 2023-01-14 at 10 36 16 PM" src="https://user-images.githubusercontent.com/77178777/212526651-a4e607f2-e0ad-48c6-bf31-1e1176b7ff68.png">

**Comment by ayn2op** [comment]
@Arian-D, fixed in the recent commit, thanks for reporting!
