### ISSUE TITLE
Reply to a message without mouse?

### ISSUE THREAD

**Issue by simbafs** [rigormorrtiss/discordo#176]
As the title says, I'm seeking a way to reply to a message with keyboard only. Is there already a keybinding?

**Comment by ghost** [comment]
1. Select a message using the arrow up and down keys (customizable) when the messages TextView is focused (you can focus on it using the `m` key).
2. Open up the message action List using the `a` key (customizable).
3. Hit the `r` key to reply to the selected message without a mention and `R` (uppercase) to reply to the selected message with a mention.

**Comment by simbafs** [comment]
thx
