### ISSUE TITLE
Do I need to run an installer to get the config.toml file?

### ISSUE THREAD

**Issue by slashdottir** [rigormorrtiss/discordo#184]
I am running the app from source on OSX and not finding this file in any of the prescribed locations.  

Can someone share a default config.toml I can install?

In particular, I'm trying to figure out the setting that will let me set the "Home" key  (in re: https://github.com/ayntgl/discordo/issues/173)

Thank you very much

**Comment by ghost** [comment]
A default configuration file is created on first start-up at `$HOME/.config/discordo/config.toml` on Unix, `$HOME/Library/Application Support/discordo/config.toml` on Darwin, and `%AppData%/discordo/config.toml` on Windows. You can configure the default configuration path using the `config` command-line flag.

**Comment by slashdottir** [comment]
@ayntgl - thank you, running the config command seems to have created it.

**Comment by slashdottir** [comment]
Hmmm, Ctrl+H isn't actually working after setting it and restarting.  It seems the app only loads a small batch of messages and you can't scroll up beyond that.  Understandable I guess because the channel in question is heavily used channel with 90 thousand messages in it as of today.

[keys]
  toggle_guilds_list = "Rune[g]"
  toggle_channels_tree_view = "Rune[c]"
  toggle_messages_text_view = "Rune[m]"
  toggle_message_input_field = "Rune[i]"
  open_message_actions_list = "Rune[a]"
  open_external_editor = "Ctrl+E"
  select_previous_message = "Up"
  select_next_message = "Down"
  select_first_message = "Ctrl+H"
  select_last_message = "End"
~                                                                                                                                                                     

no idea what "Rune" is, but I appreciate what you are doing and it must be overwhelming.  Wish for a wiki and/or FAQ

**Comment by ghost** [comment]
> It seems the app only loads a small batch of messages and you can't scroll up beyond that. Understandable I guess because the channel in question is heavily used channel with 90 thousand messages in it as of today.

The application loads 50 messages by default which is also default behavior of the official client. The limit can be changed from the configuration file using the `messages_limit` field; furthermore, the maximum limit of messages that will be fetched is 100.

> no idea what "Rune" is, but I appreciate what you are doing and it must be overwhelming.

The Go language defines the word `rune` as an alias for the type `int32`, so programs can be clear when an integer value represents a code point. For characters (though there is distinction between a character and rune), you have to wrap them in `Rune[x]`, where `x` is any character.

**Comment by slashdottir** [comment]
thank you for such detailed answers!

**Comment by slashdottir** [comment]
So, that suggests the max message limit of 100 means you can't jump to the first message in a channel unless the channel has less than 101 messages in it.
