### ISSUE TITLE
Failure to login after 2FA is requested.

### ISSUE THREAD

**Issue by auditor3d** [rigormorrtiss/discordo#185]
Panic: HTTP 400 Bad Request, {"code": 50035, "errors": {"ticket": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}, "message": "Invalid Form Body"} [recovered]
    panic: HTTP 400 Bad Request, {"code": 50035, "errors": {"ticket": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}, "message": "Invalid Form Body"}
goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
    /home/admin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/application.go:243 +0x4d
panic({0x8bd480, 0xc0004c8870})
    /usr/lib/go/src/runtime/panic.go:884 +0x212
main.main.func1.1.1()
    /home/admin/.cache/yay/discordo-git/src/discordo/main.go:98 +0x218
github.com/rivo/tview.(*Button).InputHandler.func1(0xc0000bfac0?, 0x7a001f?)
    /home/admin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/button.go:130 +0x42
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0004ee080?, 0xc0004bb650?)
    /home/admin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/box.go:167 +0x53
github.com/rivo/tview.(*Form).InputHandler.func1(0x40f507?, 0x10?)
    /home/admin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/form.go:673 +0xb7
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc00042e5a0?, 0xc0000bfbe0?)
    /home/admin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/box.go:167 +0x53
github.com/rivo/tview.(*Application).Run(0xc0002de460)
    /home/admin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/application.go:335 +0x77d
main.main.func1(0xc0002980c0?)
    /home/admin/.cache/yay/discordo-git/src/discordo/main.go:137 +0x319
github.com/urfave/cli/v2.(*App).RunContext(0xc0002ae000, {0xa1c5b0?, 0xc000026180}, {0xc000024220, 0x1, 0x1})
    /home/admin/go/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:329 +0x9fc
github.com/urfave/cli/v2.(*App).Run(...)
    /home/admin/go/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:226
main.main()
    /home/admin/.cache/yay/discordo-git/src/discordo/main.go:140 +0x309

**Comment by ghost** [comment]
#172
