### ISSUE TITLE
Feature request: option for direct messages to be a seperate panel

### ISSUE THREAD

**Issue by peepo5** [rigormorrtiss/discordo#188]
It would be cool to have the option to make direct messages a separate panel because currently you have to go to the top of the guilds list and then browse the channel section for people.

**Comment by ayntgl** [comment]
Hello there! Thank you for your suggestion. Could you please elaborate how this feature is helpful to you?

**Comment by peepo5** [comment]
This would be helpful because then it would make navigation much quicker, and it would add to the unique featureset of discordo. Having a dedicated panel would make it easier to manage direct messages and servers at the same time.
