### ISSUE TITLE
Able to login, but just presented with blank options

### ISSUE THREAD

**Issue by replicant0wnz** [rigormorrtiss/discordo#212]
I don't see any information coming in, just the various widget windows. See screenshot.

![Screenshot from 2022-09-07 16-08-35](https://user-images.githubusercontent.com/337608/188980653-9a87365f-4eb5-4143-ae95-73fc9739aa37.png)

**Comment by ghost** [comment]
Hey there! Could you provide reproducible steps so that I can look into this issue?

**Comment by replicant0wnz** [comment]
Sure! 

`discordo -token "Bot XXXXXX"`

And then the above screen pop's up. If needed I can add any recommended traces to the code and re-run ..

**Comment by ghost** [comment]
> Sure!
> 
> `discordo -token "Bot XXXXXX"`
> 
> And then the above screen pop's up. If needed I can add any recommended traces to the code and re-run ..

Hey there, I am unable to reproduce this issue; are you sure that the bot account that you are logging in with is in at least one guild?
