### ISSUE TITLE
Flickering on windows 

### ISSUE THREAD

**Issue by yate4** [rigormorrtiss/discordo#219]
When viewing discordo using windows command prompt (on build 21H2) the entire text flickers few times after each keystroke like if it was redrawing everything

**Comment by krisdybvik** [comment]
Its the same from a linux terminal (using debian with default config.yml, except timestamps and 15:04 format)

**Comment by ghost** [comment]
> Its the same from a linux terminal (using debian with default config.yml, except timestamps and 15:04 format)

Hello there! May I know which terminal emulator you are using so I can try to reproduce this issue?

**Comment by krisdybvik** [comment]
> > Its the same from a linux terminal (using debian with default config.yml, except timestamps and 15:04 format)
> 
> Hello there! May I know which terminal emulator you are using so I can try to reproduce this issue?

PuTTY
Release 0.76
Build platform: 64-bit x86 Windows

**Comment by krisdybvik** [comment]
This was greatly improved with latest version
