### ISSUE TITLE
4013 Invalid Intent(s) error when logging in with bot token

### ISSUE THREAD

**Issue by CatsSky** [rigormorrtiss/discordo#227]
I got the following error in my log when using bot token to login with the latest build.
```
2022/10/04 17:08:46 main.go:69: secret not found in keyring
2022/10/04 17:08:31 ws.go:16: Gateway error: websocket: close sent
2022/10/04 17:08:31 login_view.go:134: websocket closed, reason: 4013 Invalid intent(s).
ed.
```

**Comment by ghost** [comment]
Discordo ceased support for bot accounts since [this commit](https://github.com/ayntgl/discordo/commit/4b61bbf61d66ac187df54b8e0974a2030df23349).

**Comment by CatsSky** [comment]
I suggest removing the instruction of using bot account token to login in Readme.md if the feature is removed.
Which would be line 72

**Comment by ghost** [comment]
> I suggest removing the instruction of using bot account token to login in Readme.md if the feature is removed. Which would be line 72

Thanks for reporting, will do!
