### ISSUE TITLE
Missing servers from the guilds view

### ISSUE THREAD

**Issue by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [rigormorrtiss/discordo#249]
I posted this question on the discord forum, but the server is now missing.

My guilds list is missing everything except for the server I created and my direct messages.  I have to log in with the '--token' method as I have issues with captcha when using email and password, if that makes any difference.

**Comment by ghost** [comment]
Can you dump the contents of the log file located at `~/.cache/discordo.log`?

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
I'm away from my computer, but I'll be able to do it in about 8 hours.

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
This is the only item in the log:
`2022/10/17 19:40:51 application.go:111: item not found in store
`

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
I solved the problem.  I needed to reposition the servers _in the app_ (I did it in the online interface first, but this had no effect), and after doing so, all of the servers showed up in the guild list.  Adding or removing servers also did not do anything.  So far as I can tell, the only thing I did that had any effect was moving the servers around in the apps list.
