### ISSUE TITLE
 Unread channels not showing (same as #159) 

### ISSUE THREAD

**Issue by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [rigormorrtiss/discordo#250]
.cache/discordo.log:
```
2022/10/18 23:54:43 messages_view.go:56: Discord 403 error: Missing Access
2022/10/19 06:24:04 messages_view.go:56: Discord 403 error: Missing Access
2022/10/19 06:36:11 messages_view.go:56: Discord 403 error: Missing Access
```

discordo r492.fdad346-1

I have 2FA active

**Edit**: I deactivated 2FA.  This did not change the lack of unread notification.  It did eliminate the "Missing Access" error though.

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
Tested with prebuilt binary, same problem and nothing new in log.

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
This may be a related issue.  changes to the "Theme" section of config discordo.yml only take affect in the action view box.  Background, title and border changes are only shown in the action view box, not main application display.  This lack of communication for theming might also carry over to highlighting unread messages and pings?

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
Latest updates (discordo-git r497.01c75f0-1) have resolved the theming issues, but unread messages continue to lack indicators, so those two issues were not connected.

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
I want to add that I installed cordless (https://github.com/Bios-Marcel/cordless) and while unmaintained, it was still sufficiently functional to see if an alternate client could detect when I had unread channels and servers.  Unread channel/server detection and indication work for my account in cordless.

**Comment by ayn2op** [comment]
Unfortunately, I am not unable to reproduce this issue, can you use the `rewrite` branch instead and see if the issue persists?
