### ISSUE TITLE
Failed to build on GNU/Linux Ubuntu 22.04 

### ISSUE THREAD

**Issue by vanfanel** [rigormorrtiss/discordo#252]
Hi there,

This is my first time building a "go" program, so I am sorry if I did something wrong.

I installed the "go" compiler like this:
`sudo apt-get install gccgo-go`

Then, I did this:
`go mod download github.com/gdamore/tcell/v2`

Then I tried to build with
`make build -j4`

But I get:
```

go build -ldflags "-s -w"
../../go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: //go:build comment without // +build comment
ui/login_view.go:10:2: //go:build comment without // +build comment
make: *** [Makefile:16: build] Error 1

```

Any idea on what's going on? Some omission on my side, for sure, but what?

Thanks!

**Comment by ghost** [comment]
`gcc-go` does not support the latest version of Go; please use the `gc` compiler instead.

**Comment by vanfanel** [comment]
@ayntgl Thanks! Do you know the name Debian/Ubuntu for the gc package I need?

**Comment by ghost** [comment]
Depending on the repository that you have enabled, you might get different versions:
```bash
sudo apt install golang
```

Read more: https://github.com/golang/go/wiki/Ubuntu

**Comment by vanfanel** [comment]
@ayntgl Got it to work, thanks a lot!
