### ISSUE TITLE
Can't see channels

### ISSUE THREAD

**Issue by vanfanel** [rigormorrtiss/discordo#253]
Hi there,

Even if I was finally able to build and log into discordo using my discord user/pass, I can't see the servers or channels listed anywhere. I can only see the PMs listed under the channels window, which is somewhat confusing.

Looking at the instructions, they don't mention anything special should be done.

So, how can I make servers & channel show up on discordo? I mean, the ones I am joined in.

Thanks!

**Comment by ghost** [comment]
Can you dump the contents of the log file located at `~/.cache/discordo.log`?

**Comment by vanfanel** [comment]
@ayntgl Yes, of course:
```

manuel@vader:~$ cat ~/.cache/discordo.log 
2022/10/24 12:15:10 main.go:47: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'
2022/10/24 12:16:06 application.go:83: read /dev/tty: input/output error
y: {"email": {"_errors": [{"code": "INVALID_LOGIN", "message": "Login or password is invalid."}]}, "password": {"_errors": [{"code": "INVALID_LOGIN", "message": "Login or password is invalid."}]}}
```

Strange... it says invalid login, yet I can see my conversations?

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
Try this: https://github.com/ayntgl/discordo/issues/249#issuecomment-1283422894

**Comment by vanfanel** [comment]
@ayntgl Wow, that worked. Yep. Moved some servers around, and now all of them are visible on Discordo.
Strange! But it works!
