### ISSUE TITLE
Feature request: hide inaccessible channels

### ISSUE THREAD

**Issue by acid-bong** [rigormorrtiss/discordo#254]
OS: Artix Linux
Discordo: built from master commit 02a8dbd (HEAD as i'm writing this)

I've been checking my servers and on every server (where they exist, presumably) in the channel list i started seeing channels i should not be able to see - channels for mods, patrons etc (i'm neither of those anywhere). When selected, the content, luckily, isn't revealed; i didn't risk\* trying to send a message in one. Either Discord's API isn't as bulletproof, or discordo is too invasive.

Other clients: haven't compared, but i don't remember that issue from the past.

**Comment by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [comment]
I have experienced this as well.  And I have been using cordless, a defunct TUI client for testing purposes, and I can confirm that the hidden channels do not show up in it.

**Comment by ghost** [comment]
same issue, could be easily fixed by simply skipping those channels (or maybe making it an option for the people who want to do some epic trolling?)

**Comment by txtsd** [comment]
They are exposed via the API. The client chooses whether or not to show them.

**Comment by ayn2op** [comment]
You cannot successfully send a message in an inaccessible channel, but they are returned by the API; so it is not Discordo being evasive, but the Discord API. I do agree that Discordo should ignore the inaccessible channels by checking that whether the client user has the permission to read messages in that channel like the official client, this should be fairly easy to implement.

**Comment by sewnie** [comment]
nooo not my heckin hidden channels i wanna see what they do be hiding

**Comment by sewnie** [comment]
can we unironically have a plugin that disables this

**Comment by ayn2op** [comment]
> can we unironically have a plugin that disables this

Plugins are not supported yet, but if and when they are, you should be able to easily disable this behavior.
