### ISSUE TITLE
Feature Request: "Escape" or any key bind for exit message input box and out from program

### ISSUE THREAD

**Issue by hafizdkren** [rigormorrtiss/discordo#256]
I've been back to discordo again to testing the features. It seem already had lot improvement like notification and more.

But, there still a lot of basic stuff which being lost in either by ignorance or is just me which forgot which key bind is for what. This is a highly level of importance, even if reading and edit the config or even check the git itself. not everyone is like to had difficulty to exit (like many people do when try vim for first time, which being fixed by neovim team by setup the tutorial on web too...)

I know this seem not looks like what open-source or linux user supposed to say, but sometimes project like these is too good to be ignore. if somebody found it amazing, it would be a bummer for them to be feel difficult right in the first step...

Some good idea I can give, since IDK golang language in first place.
[] Showing some key bind with simple explain such "{` + a} open message menu"
[] Adding some configuration for exit input, switch from guild channel and message

Hope the best from you, I hope this project would growth greatly...

**Comment by ghost** [comment]
Thanks for the feedback, @hafizdkren! The `Escape` key "unfocuses" the input view (`*tview.InputView`) and sets the focus to the main flex (`*tview.MainFlex`). `Ctrl` + `C` can be used to exit the program. I do agree that the project needs more documentation, feel free to open a PR.

**Comment by PseudoDistant** [comment]
While Ctrl + C works for me, Esc doesn't...
I'm running on a Debian install with no GUI.
