### ISSUE TITLE
Messages flow in from every channel at once, rather than just the selected one...

### ISSUE THREAD

**Issue by amenokagaseo** [rigormorrtiss/discordo#257]
Expected behaviour should be that selecting a channel would only show messages from that channel, but instead selecting a channel shows the messages belonging to that channel before flooding the chatlog (visually) with spam from other channels or even *servers*.

![image](https://user-images.githubusercontent.com/114450238/203484704-34418b16-f4a6-48a5-b14b-e55d8e23afad.png)
Note how, despite having no channel selected at all, I'm still receiving a flood of messages from random servers.

**Comment by amenokagaseo** [comment]
Note that I'm using the discordo-git package from the AUR, which appears to be significantly out of date.

**Comment by viridivn** [comment]
I'm also having this issue (arch linux aarch64). Happy to provide any logs or debugging stuff that might help.

**Comment by ghost** [comment]
Hello there! Thanks for reporting; unfortunately, I am unable to reproduce this issue, can you provide reproducible steps so that I can look into this issue?

**Comment by viridivn** [comment]
Hmm. I just deleted the discordo yml as I was going to fresh install to provide steps, and I can no longer reproduce. I'll keep investigating.

**Comment by viridivn** [comment]
Found something. With notifications enabled in the config yml, it works as expected. Disable notifications, and the message problem occurs. I use the discordo-git package in the AUR.

**Comment by emanueljg** [comment]
This problem still occurs for me (NixOS). Newest commit post-fix, tried turning notificactions both on and off. Still getting messages from other channels. Perhaps worth mentiong is that I won't get messages if I have no channel selected as OP mentioned - but it does occur when I choose an arbitrary channel, then it starts showing messages from all other channels.

**Comment by takomine** [comment]
I'm having the exact same issue right now. Chat messages from other groups keeps appearing

OS: Windows 10 LTSC (21H2)

**Comment by viridivn** [comment]
Issue still occurs with me as well, albeit in a slightly different form. Upon first launch, no problems. However, as soon as you select a server/channel, all the messages stream in from many channels.

Edit: oops, nevermind! I didn't see the most recent commit - that fixes it. Thanks devs!
