### ISSUE TITLE
500 error on the Nightly binaries link

### ISSUE THREAD

**Issue by zilpe** [rigormorrtiss/discordo#259]
Hello

When clicking on the link to the binaries (https://nightly.link/ayntgl/discordo/workflows/ci/main), there is an internal server error 500.

Thanks!

**Comment by sewnie** [comment]
https://nightly.link/ayn2op/discordo/workflows/ci/main

**Comment by sewnie** [comment]
@ayn2op update the README main thing to your new username.

**Comment by ayn2op** [comment]
Thanks for reporting!
