### ISSUE TITLE
Sending messages once channel is closed sends them to the last channel

### ISSUE THREAD

**Issue by Zstorm999** [rigormorrtiss/discordo#262]
I don’t know if this is an intended feature, but sending a message after closing a channel with [ESC] [ESC] sends the message to the last opened channel.

Configuration : 
**Manjaro on Linux 5.19, zsh**

[before](https://cdn.discordapp.com/attachments/669471989915713556/1056246352809566208/image.png)
[sending the message](https://cdn.discordapp.com/attachments/669471989915713556/1056246465774751744/image.png)
[the resulting message](https://cdn.discordapp.com/attachments/669471989915713556/1056246532556476426/image.png)

**Comment by sewnie** [comment]
escape isn't supposed to do anything?

**Comment by Zstorm999** [comment]
Maybe that’s where the problem is coming from

**Comment by ayn2op** [comment]
Thanks for reporting! #264 should fix this issue.
