### ISSUE TITLE
Feature request: Uploading files

### ISSUE THREAD

**Issue by ghost** [rigormorrtiss/discordo#263]
Maybe I just can't find it, but it seems like it's impossible to send an attached image or file. This is a quite useful feature and I'd like to see it implemented in Discordo.

**Comment by sewnie** [comment]
wait wtf was this not possible

**Comment by ayn2op** [comment]
Hello there, Discordo aims to be lightweight and minimalistic, with prime focus on performance. It utilizes the [tview](https://github.com/rivo/tview) library which is built on top of [tcell](https://github.com/gdamore/tcell). Though tview has plenty of widgets and it is very feature-rich, it lacks flexibility. I am considering implementing a plugin system to allow users to implement plugins to extend functionality and customize the functionality of the application by installing and uninstalling plugins. Is this sufficient for your needs?

**Comment by ghost** [comment]
it would be good @ayn2op

**Comment by ghost** [comment]
> Hello there, Discordo aims to be lightweight and minimalistic, with prime focus on performance. It utilizes the [tview](https://github.com/rivo/tview) library which is built on top of [tcell](https://github.com/gdamore/tcell). Though tview has plenty of widgets and it is very feature-rich, it lacks flexibility. I am considering implementing a plugin system to allow users to implement plugins to extend functionality and customize the functionality of the application by installing and uninstalling plugins. Is this sufficient for your needs?

A plugin system would be fantastically useful and definitely should be added, and I think it would work fine as a plugin -- but I think it would probably be a better implementation to just add it straight into the client to create less confusion and hassle, especially with a function as important as that.

That being said, it wouldn't kill anyone to use it as a plugin and regardless a plugin system would be fantastic

**Comment by sewnie** [comment]
What about patches? They are exponentionally easier than implementing a plugin system

**Comment by ayn2op** [comment]
Duplicate: #162
