### ISSUE TITLE
not starting on arch linux

### ISSUE THREAD

**Issue by graziel666** [rigormorrtiss/discordo#264]
as the tittle says, since some days ago i'm trying to use discordo but it just doesnt start, no error of any kind, and using discordo --help shows the help message at least, but when i type discordo and hit enter, the cursor just blinks, skips a line and nothing happens

![image](https://user-images.githubusercontent.com/35145859/209487494-0ccec334-2233-4a59-b0a0-f2e39d903af0.png)

any idea what can this be?

**Comment by sewnie** [comment]
`strace discordo`

**Comment by ayn2op** [comment]
Can you dump the content of the log file (located at `~/.cache/discordo/logs.txt` on Unix-based platforms) here?

**Comment by graziel666** [comment]
` websocket closed, reason: 4004 Authentication failed.`

only had that on the log, still after seeing this i remembered i did an alias on zsh with the discord -token 
still, comenting out that alias didn't worked for some reason, but checking it, i noticed that my token was diferent now with the one i was using until now, after changing it to the new correct one it started working again as normal

checked again comenting my alias and now i'm getting the login screen too
