### ISSUE TITLE
Feature Request: Change highlight color.

### ISSUE THREAD

**Issue by JSybrandt** [rigormorrtiss/discordo#267]
I just installed discordo and I'm loving it!

I have an issue where the highlight background color used to select a channel / server is the same as the foreground color for displaying the name of that channel / guild. The end result is that its pretty difficult to select the channel I'm looking for.

Anyways, just wanted to give you a heads up on this little usability quirk. Thanks for putting this project together!

**Comment by ayn2op** [comment]
Looks like `tview` does not allow users to modify highlight style, it uses the reverse attribute instead for highlights.
