### ISSUE TITLE
"Exec format error" on Raspberry Pi 3/Debian

### ISSUE THREAD

**Issue by livvy94** [rigormorrtiss/discordo#276]
Hello! I downloaded the precompiled Linux build with `wget` and unzipped it, but upon `chmod a+x`'ing it and running it, it says: 
```-bash: ./discordo: cannot execute binary file: Exec format error```
Was it compiled with a different Linux distro or in mind or am I doing something wrong?
Either way I'll try to build from source instead and see how that goes. Thank you so much for making this, I use a tiny B&W portable CRT TV as a display for my Raspberry Pi and using discord on it would be cool as hell.

**Comment by sewnie** [comment]
It obviously will not work as the binary builds were intended for x86_64, you must compile discordo natively for your pi (arm)'s architecture.

**Comment by livvy94** [comment]
Oh, that makes sense. 

I just tried to compile from source, and running `go build` doesn't produce any binaries and says:
```../../go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/olivia/go/pkg/mod/github.com/rivo/uniseg@v0.4.3```

(I apologize, I have never used golang before)

EDIT: I'm running `go version go1.15.15 linux/arm64`

**Comment by sewnie** [comment]
`go build -modcacherw`

**Comment by livvy94** [comment]
I just tried this and it gives the same error message about the packages.
EDIT: running `sudo go build -modcacherw` makes it print all the packages it's able to successfully download again:
```go: downloading github.com/diamondburned/arikawa/v3 v3.2.0
go: downloading github.com/zalando/go-keyring v0.2.2
go: downloading github.com/atotto/clipboard v0.1.4
go: downloading github.com/rivo/tview v0.0.0-20230104153304-892d1a2eb0da
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/gdamore/tcell/v2 v2.5.4
go: downloading github.com/godbus/dbus/v5 v5.1.0
go: downloading golang.org/x/text v0.6.0
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading golang.org/x/term v0.4.0
go: downloading golang.org/x/sys v0.4.0
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/gorilla/schema v1.2.0
go: downloading golang.org/x/time v0.3.0
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/rivo/uniseg v0.4.3
/root/go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /root/go/pkg/mod/github.com/rivo/uniseg@v0.4.3```

**Comment by sewnie** [comment]
Well I don't know much about setup of Go on other architectures, consult arbitrary documentation about it perhapd

**Comment by ayn2op** [comment]
@livvy94 https://github.com/golang/go/wiki/GoArm

**Comment by ayn2op** [comment]
@livvy94 @livvy94 https://github.com/golang/go/wiki/GoArm

```bash
GOARCH=arm64 go build .
```

**Comment by ayn2op** [comment]
Try to build the binary from the latest commit:

```
git clone https://github.com/ayn2op/discordo
cd discordo
go build -v .
```

**Comment by livvy94** [comment]
Unfortunately it's still giving the same message... 
`../../go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/olivia/go/pkg/mod/github.com/rivo/uniseg@v0.4.3`

Same with `go build -modcacherw`

**Comment by sewnie** [comment]
ayn2op try not to close issue without original creator verifying its fixed challenge

**Comment by ayn2op** [comment]
> Oh, that makes sense.
> 
> I just tried to compile from source, and running `go build` doesn't produce any binaries and says: `../../go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/olivia/go/pkg/mod/github.com/rivo/uniseg@v0.4.3`
> 
> (I apologize, I have never used golang before)
> 
> EDIT: I'm running `go version go1.15.15 linux/arm64`

The minimum Go version required to compile Discordo is `1.19`. Please upgrade the Go toolchain and try again.

**Comment by livvy94** [comment]
After a lot of wrestling with golang's downloads (I'm on a raspberry pi so apt-get has an old version), I was able to install 1.20 and build the code! Thank you for being patient with me.
