### ISSUE TITLE
Not starting on Arch as a user; can't view direct messages when running as sudo

### ISSUE THREAD

**Issue by vanillyn** [rigormorrtiss/discordo#278]
![image](https://user-images.githubusercontent.com/108785622/215647054-3e9b941f-f8e4-4d73-acd5-1861db40dbf1.png)
(running as sudo)
[strace when running as user](https://lsafe.vanillyn.tk/PQJWMmMC.txt)
[strace -eopen when running as user](https://lsafe.vanillyn.tk/QIqIpPio.txt)
[discordo log when running as user](https://lsafe.vanillyn.tk/TFVJKwhd.txt)

**Comment by sewnie** [comment]
You're never meant to run programs like this as superuser..

**Comment by ayn2op** [comment]
Your configuration file is outdated; delete the current configuration file and rerun the program and a new configuration file will be created automatically.

**Comment by vanillyn** [comment]
> You're never meant to run programs like this as superuser..

yeah, I don't understand why it's not working without superuser



> Your configuration file is outdated; delete the current configuration file and rerun the program and a new configuration file will be created automatically.

I'll try it

**Comment by vanillyn** [comment]
I've restarted it after deleting the configuration file, but I got this error after logging in:
```
panic: runtime error: index out of range [4] with length 4 [recovered]
        panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:244 +0x4d
panic({0x93fde0, 0xc0006cc000})
        /usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/rivo/tview.(*Form).GetFormItem(...)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/form.go:407
main.(*LoginForm).onLoginButtonSelected(0xc000318018)
        /home/vani/.cache/yay/discordo-git/src/discordo/login_form.go:75 +0x3b9
github.com/rivo/tview.(*Button).MouseHandler.func1(0x3, 0xc00029dbb0?, 0x792cdf?)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/button.go:161 +0x7a
github.com/rivo/tview.(*Box).WrapMouseHandler.func1(0xa0?, 0x0?, 0x7f6dbe367e18?)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/box.go:209 +0x53
github.com/rivo/tview.(*Form).MouseHandler.func1(0x3, 0xc00028e5a0, 0x10?)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/form.go:770 +0x127
github.com/rivo/tview.(*Box).WrapMouseHandler.func1(0x8000?, 0xc00029ddd0?, 0x449bf4?)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/box.go:209 +0x53
github.com/rivo/tview.(*Application).fireMouseActions.func1(0x6500?)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:430 +0x182
github.com/rivo/tview.(*Application).fireMouseActions(0xc0001f6380, 0xc00028e5a0)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:467 +0x2ee
github.com/rivo/tview.(*Application).Run(0xc0001f6380)
        /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:366 +0x8aa
main.main()
        /home/vani/.cache/yay/discordo-git/src/discordo/main.go:68 +0x171
```

**Comment by ayn2op** [comment]
> I've restarted it after deleting the configuration file, but I got this error after logging in:
> 
> ```
> panic: runtime error: index out of range [4] with length 4 [recovered]
>         panic: runtime error: index out of range [4] with length 4
> 
> goroutine 1 [running]:
> github.com/rivo/tview.(*Application).Run.func1()
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:244 +0x4d
> panic({0x93fde0, 0xc0006cc000})
>         /usr/lib/go/src/runtime/panic.go:884 +0x212
> github.com/rivo/tview.(*Form).GetFormItem(...)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/form.go:407
> main.(*LoginForm).onLoginButtonSelected(0xc000318018)
>         /home/vani/.cache/yay/discordo-git/src/discordo/login_form.go:75 +0x3b9
> github.com/rivo/tview.(*Button).MouseHandler.func1(0x3, 0xc00029dbb0?, 0x792cdf?)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/button.go:161 +0x7a
> github.com/rivo/tview.(*Box).WrapMouseHandler.func1(0xa0?, 0x0?, 0x7f6dbe367e18?)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/box.go:209 +0x53
> github.com/rivo/tview.(*Form).MouseHandler.func1(0x3, 0xc00028e5a0, 0x10?)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/form.go:770 +0x127
> github.com/rivo/tview.(*Box).WrapMouseHandler.func1(0x8000?, 0xc00029ddd0?, 0x449bf4?)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/box.go:209 +0x53
> github.com/rivo/tview.(*Application).fireMouseActions.func1(0x6500?)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:430 +0x182
> github.com/rivo/tview.(*Application).fireMouseActions(0xc0001f6380, 0xc00028e5a0)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:467 +0x2ee
> github.com/rivo/tview.(*Application).Run(0xc0001f6380)
>         /home/vani/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:366 +0x8aa
> main.main()
>         /home/vani/.cache/yay/discordo-git/src/discordo/main.go:68 +0x171
> ```

You are running an older version; try building from source using the most recent commit.

```bash
git clone https://github.com/ayn2op/discordo
cd discordo
go build .
```

**Comment by vanillyn** [comment]
It seems to work after building it.
However, I still can't view DMs, maybe I'm missing a keybind?

**Comment by ayn2op** [comment]
> It seems to work after building it. However, I still can't view DMs, maybe I'm missing a keybind?

@vanillyn, please join the [Discord server](https://discord.gg/Gx48RRmKvx) so I can troubleshoot the issue further.
