### ISSUE TITLE
Panic Crash while logging in from 2FA account

### ISSUE THREAD

**Issue by iamcodernitesh** [rigormorrtiss/discordo#28]
Installed using AUR. Crashes when Trying to login with a 2 factor authentication enabled account.

```
panic: account has 2FA enabled [recovered]
	panic: account has 2FA enabled

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc00021e000)
	/home/niteshk/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/application.go:243 +0x87
panic(0x883f80, 0xc00000e270)
	/usr/lib/go/src/runtime/panic.go:965 +0x1b9
main.newSession(0xc000402ea0, 0x1a, 0xc00046e140, 0xe, 0x0, 0x0, 0xc000088800)
	/home/niteshk/.cache/yay/discordo-git/src/discordo/discordo.go:126 +0x306
main.onLoginFormLoginButtonSelected()
	/home/niteshk/.cache/yay/discordo-git/src/discordo/discordo.go:267 +0x152
github.com/rivo/tview.(*Button).InputHandler.func1(0xc0003e7020, 0xc0003ea810)
	/home/niteshk/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/button.go:129 +0x6a
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0003e7020, 0xc0003ea810)
	/home/niteshk/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/box.go:161 +0x62
github.com/rivo/tview.(*Form).InputHandler.func1(0xc0003e7020, 0xc0003ea810)
	/home/niteshk/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/form.go:673 +0xee
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0003e7020, 0xc0003ea810)
	/home/niteshk/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/box.go:161 +0x62
github.com/rivo/tview.(*Application).Run(0xc00021e000, 0x0, 0x0)
	/home/niteshk/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/application.go:335 +0x7a7
main.main()
	/home/niteshk/.cache/yay/discordo-git/src/discordo/discordo.go:70 +0x40d
```

**Comment by rigormorrtiss** [comment]
@iamcodernitesh #29 added support for MFA (2FA) logins

**Comment by iamcodernitesh** [comment]
Tried using logging in again. and it asked for code. After adding code it shows something like this https://i.imgur.com/gEEZjPM.png
. and it triggers some keys as shown in the image linked.

**Comment by rigormorrtiss** [comment]
> Tried using logging in again. and it asked for code. After adding code it shows something like this https://i.imgur.com/gEEZjPM.png
> . and it triggers some keys as shown in the image linked.

Hey @iamcodernitesh, could you provide additional useful information such as which desktop environment (if any) or window manager you are currently using? Do you have a keyring (usually GNOME Keyring) set up?

**Comment by iamcodernitesh** [comment]
> > Tried using logging in again. and it asked for code. After adding code it shows something like this https://i.imgur.com/gEEZjPM.png
> > . and it triggers some keys as shown in the image linked.
> 
> Hey @iamcodernitesh, could you provide additional useful information such as which desktop environment (if any) or window manager you are currently using? Do you have a keyring software (usually GNOME Keyring) installed and set up?

I am using i3 window manager on Arch Linux 5.13.10-zen1-1-zen. I don't have gnome keyring install.

**Comment by rigormorrtiss** [comment]
> I am using i3 window manager on Arch Linux 5.13.10-zen1-1-zen. I don't have gnome keyring install.

i3 does not have a default or official keyring software. You should check out [Pass](https://www.passwordstore.org/) instead.

**Comment by rigormorrtiss** [comment]
> > > Tried using logging in again. and it asked for code. After adding code it shows something like this https://i.imgur.com/gEEZjPM.png
> > > . and it triggers some keys as shown in the image linked.
> > 
> > 
> > Hey @iamcodernitesh, could you provide additional useful information such as which desktop environment (if any) or window manager you are currently using? Do you have a keyring software (usually GNOME Keyring) installed and set up?
> 
> I am using i3 window manager on Arch Linux 5.13.10-zen1-1-zen. I don't have gnome keyring install.

@iamcodernitesh, #30 added support for `DISCORDO_TOKEN` environment variables.
