### ISSUE TITLE
Image & Videos

### ISSUE THREAD

**Issue by h4636oh** [rigormorrtiss/discordo#283]
why not use sxiv and mpv to display them instead of having the as a regular link to open them in browser

**Comment by sewnie** [comment]
#241

**Comment by ayn2op** [comment]
@apprehensions this is an old PR; attachments are no longer launched using default applications (`xdg-open` for Linux).

**Comment by sewnie** [comment]
ok how are they launched now

**Comment by r3k2** [comment]
sixel will be a good way to show images

**Comment by ayn2op** [comment]
https://github.com/gdamore/tcell/pull/602

**Comment by HalanoSiblee** [comment]
use ffplay to view and play video , audio,also view images

**Comment by Edwardtw92** [comment]
@HalanoSiblee do you mind specifying how? I am using Kitty on Linux and can't figure out to use ffplay to view and play video from Discordo.

**Comment by ayn2op** [comment]
> why not use sxiv and mpv to display them instead of having the as a regular link to open them in browser

Can sxiv or mpv open links? I don't think it is a good idea to download an attachment from Discord.

**Comment by ayn2op** [comment]
Just set `sxiv` or `mpv` as default application from settings and you should be good to go.
