### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by r3k2** [rigormorrtiss/discordo#285]
Just download it to give it a try under Arch GNU/Linux using Wayland/sway and when I try to put email/pass it crashes to bash shell.
- terminal: Foot
- Wayland
- Sway
- Arch GNU/Linux
There is no output to paste, just ends and shows the bash prompt.

**Comment by sewnie** [comment]
Have a look at logs in `~/.cache/discordo` or run `strace discordo`.

**Comment by sewnie** [comment]
Also this isn't really a crash, rather just an exit, as it doesn't seem a return code was provided.

**Comment by r3k2** [comment]
ok, I have checked there and I have:

```
.cache/paru/clone/discordo-git/src/discordo/internal/ui/login_form.go:54: Discord returned status 400 body {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-XXXXXXXXXXXXX", "captcha_service": "hcaptcha"}
```

**Comment by ayn2op** [comment]
> ok, I have checked there and I have:
> 
> ```
> .cache/paru/clone/discordo-git/src/discordo/internal/ui/login_form.go:54: Discord returned status 400 body {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-XXXXXXXXXXXXX", "captcha_service": "hcaptcha"}
> ```

https://github.com/ayn2op/discordo/issues/86
