### ISSUE TITLE
Missing guilds/groups

### ISSUE THREAD

**Issue by r3k2** [rigormorrtiss/discordo#287]
I got invited last night to a guild, I don't use discordo much, I have been using revolt.chat more, but sporadically, I do need to open it, so this is why discordo is nice, but I log in today and I am missing one guild/group that I got invited to yesterday... is this a known problem or I have to do something to refresh somehow the list?

**Comment by Magissia** [comment]
Facing the same issue but worse, only DMs are shown, everything else is missing on the left tree.

**Comment by emanueljg** [comment]
I can confirm this bug's existence and it shows up for me every now and then when joining new servers, but for me it resolves itself after relogging after some time, eventually the new server does show up in the list.

**Comment by ghost** [comment]
> Facing the same issue but worse, only DMs are shown, everything else is missing on the left tree.

I have the same exact issue. Just DMs show up.

Plus, the screen flickers wildly everytime I move the mouse.

**Comment by M3M3STUFF** [comment]
> I can confirm this bug's existence and it shows up for me every now and then when joining new servers, but for me it resolves itself after relogging after some time, eventually the new server does show up in the list.

how long is some time?

**Comment by emanueljg** [comment]
> > I can confirm this bug's existence and it shows up for me every now and then when joining new servers, but for me it resolves itself after relogging after some time, eventually the new server does show up in the list.
> 
> how long is some time?

I've seen it being done in minutes, hours and I think days even. But take this with a grain of salt as I rarely join new servers so the bug might be more prevalent or does not resolve at times. 

What i can say though, is that the bug is a mystery to me. I've worked with discordo when implementing #307 and as such explored how channels are fetched. It's done in [cmd/run/state.go's onReady function](https://github.com/ayn2op/discordo/blob/main/cmd/run/state.go#L57C7-L57C7) and to me it seems pretty airtight, making the bug even more esoteric.

**Comment by jwallden** [comment]
> > > I can confirm this bug's existence and it shows up for me every now and then when joining new servers, but for me it resolves itself after relogging after some time, eventually the new server does show up in the list.
> > 
> > 
> > how long is some time?
> 
> I've seen it being done in minutes, hours and I think days even. But take this with a grain of salt as I rarely join new servers so the bug might be more prevalent or does not resolve at times.
> 
> What i can say though, is that the bug is a mystery to me. I've worked with discordo when implementing #307 and as such explored how channels are fetched. It's done in [cmd/run/state.go's onReady function](https://github.com/ayn2op/discordo/blob/main/cmd/run/state.go#L57C7-L57C7) and to me it seems pretty airtight, making the bug even more esoteric.

Got this also. I only see Direct Messages in the list. No servers. No change after relogging.

**Comment by rarecoil** [comment]
+1 to this bug happening to me in alacritty on X11 / i3. I only get direct messages.

**Comment by gangstertoppen** [comment]
Still present on my machine, only getting direct messages.
Logging in with token or email does not make a difference.

OS: Debian GNU/Linux Rolling x86_64
Shell: zsh 5.9                                                                                                                                        
CPU: Intel i3-8130U (4) @ 3.400GHz
DE: Xfce 4.18
Terminal: qterminal

**Comment by ouwou** [comment]
i would bet this is because discord does not actually send all guild IDs in `UserSettings.GuildFolders`. remaining guilds are inserted in descending order by ID at the top
as a workaround u can just drag missing guilds around in the official client which should force update the folders user setting

**Comment by r3k2** [comment]
Hello giving discordo another try, just wanted to report that 
- now I can login with username/pass (but still does not stick when I re-open)
- I so far can see all my discord "groups" 
I did notice that:
- I do not see all the chat channels in some discord groups, like in particular I see some is missing a few that are under 1 topic for example: 
            - Topic 
                -- chat 1 
                -- chat 2
                -- chat 3 
             
so far that is the only issue I see of course other than the no voice chat capable :) :)  and not having vim keys , I hate using the mouse. :(

**Comment by opeyer** [comment]
Also reporting that only DMs show up. I've played around with the order and such for a few days, but it's still nothing but the DMs.

**Comment by personalhel** [comment]
> i would bet this is because discord does not actually send all guild IDs in `UserSettings.GuildFolders`. remaining guilds are inserted in descending order by ID at the top as a workaround u can just drag missing guilds around in the official client which should force update the folders user setting

this worked for me. thank you!
