### ISSUE TITLE
ban chances?

### ISSUE THREAD

**Issue by antgame11** [rigormorrtiss/discordo#288]
How likely will I be banned for using this?

**Comment by sewnie** [comment]
> Automated user accounts or "self-bots" are against Discord's Terms of Service. I am not responsible for any loss caused by using "self-bots" or Discordo.

Likely? 10%. But as Discord is a shitty service you shouldn't worry about it.

**Comment by Matthieu-LAURENT39** [comment]
> > Automated user accounts or "self-bots" are against Discord's Terms of Service. I am not responsible for any loss caused by using "self-bots" or Discordo.
> 
> Likely? 10%. But as Discord is a shitty service you shouldn't worry about it.

Fun fact: 97% of statistics are made up (source: i made it up)

Seriously though, it's pretty much impossible to reply correctly to this issue. 
From what i've heard, no one has gotten banned for using Discordo *so far*, but the risk will always be there as using 3rd party clients is against discord's TOS.

It's up to you to weight if you want to take the risk or not
