### ISSUE TITLE
Image view mode

### ISSUE THREAD

**Issue by DeaDvey** [rigormorrtiss/discordo#289]
This might be a stupid question, but how do I leave the image view mode, currently the config.yml file shows how to show image but not how to leave this mode.
Thanks - DeaDvey

**Comment by ayn2op** [comment]
Click on the widget to focus on it, hit Escape to go back.

**Comment by DeaDvey** [comment]
Hmm, this doesn't seem to be working for me, do I have to add it to my config file? If so what is the syntax? If not are there any other possible keys?
Thanks again - DeaDvey

**Comment by NickHastings** [comment]
> Click on the widget to focus on it, hit Escape to go back.

Is there any way to do this without having to Click with mouse/pointer? Ie just keyboard?

**Comment by ayn2op** [comment]
The Image widget should be automatically focused when it is set as root widget, but that's not happening due to [a bug in tview](https://github.com/rivo/tview/pull/845). When the image widget is focused, you should be able to press `Escape` to go back to the previous widget (Flex). The keybinding to display the image can be customized from the configuration file (default: `i`).

**Comment by DeaDvey** [comment]
Is there a keybind to focuse on the image widgit? I cannot see a bind for it in my config.yml; I have also tried a plethera of possibilities (Mostly by wacking my keyboard) but cannot seem to find a bind to focus the image widgit.
Thanks - DeaDvey
`mouse: false
messages_limit: 50
timestamps: false
editor: default
keys:
    cancel: Esc
    guilds_tree:
        focus: Alt+Rune[g]
    messages_text:
        focus: Alt+Rune[m]
        show_image: Rune[i]	
        copy_content: Rune[c]
        reply: Rune[r]
        reply_mention: Rune[R]
        select_reply: Rune[s]
        select_previous: Up
        select_next: Down
        select_first: Home
        select_last: End
    message_input:
        focus: Alt+Rune[i]
        send: Enter
        paste: Ctrl+V
        launch_editor: Ctrl+E
theme:
    border: true
    border_color: default
    border_padding: [0, 0, 1, 1]
    title_color: default
    background_color: default
    guilds_tree:
        graphics: true
    messages_text:
        author_color: aqua
    message_input: {}
`

**Comment by ayn2op** [comment]
The Image widget is now focused when it is set a root, so you do not need to manually focus it by clicking on it.

**Comment by DeaDvey** [comment]
Thanks :D Doesn't seem to work right now, but I'll try again tommorow.
Thanks - DeaDvey
