### ISSUE TITLE
Prebuilt binary loads as a document.

### ISSUE THREAD

**Issue by abbylyra** [rigormorrtiss/discordo#293]
The MacOS binary will unzip and end up as a "document".

**Comment by sewnie** [comment]
where are you getting the binary from...?

**Comment by ayn2op** [comment]
@apprehensions https://github.com/ayn2op/discordo#prebuilt-binaries

**Comment by ayn2op** [comment]
@Happpydust, unzip the binary and change the file mode to executable (`chmod +x ./discordo`).

```sh
unzip ./path/to/file.zip
chmod +x ./discordo
./discordo
```

**Comment by abbylyra** [comment]
Thanks, that fixed it.
