### ISSUE TITLE
how to close application?

### ISSUE THREAD

**Issue by irtusb** [rigormorrtiss/discordo#295]
tried every key combo, and the only one that works is terminate it with a process manager

**Comment by Mattlau04** [comment]
What's your setup?
Ctrl+C works for me on Linux with the Konsole terminal

**Comment by Matthieu-LAURENT39** [comment]
What's your setup?
Ctrl+C works for me on Linux with the Konsole terminal

**Comment by irtusb** [comment]
it works now ... it launched the $EDITOR but hanged and that stopped client from doing anything
