### ISSUE TITLE
not loading in terminal [on arch via yay]

### ISSUE THREAD

**Issue by Halem998** [rigormorrtiss/discordo#299]
Upon typing "discordo" in CLI i get weird behaviour. I dont get an error message.
It just keep loading or so it seems.
Once i got the login menu launched. 
The other time when closing the "loading" window i briefly could see the TUI.
Kinda weird. 

Any idea?

**Comment by Halem998** [comment]
i got to load the TUI again: this time by hitting enter 3 times while loading/running. can't reproduce.

**Comment by txtsd** [comment]
Some logs will help.

**Comment by Halem998** [comment]
which logs? when i type discordo -v / -d nothing happens. syslogs? st? dwm?  sorry i'm a noob

edit: when i look into the logfile of discordo, it's empty: $HOME/.cache/discordo/logs.txt

**Comment by Halem998** [comment]
OK I got it. It's loading ages, it's as simple as that. I just have to wait so long, unusual.

**Comment by ghost** [comment]
If anyone else gets this, the error is `failed to get token from keyring: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)`
