### ISSUE TITLE
Upload to homebrew?

### ISSUE THREAD

**Issue by nyngwang** [rigormorrtiss/discordo#305]
As title. I'm a macOS user and I like homebrew 🥺 .

**Comment by sewnie** [comment]
You may consider maintaining the homebrew package for discordo yourself.

**Comment by ayn2op** [comment]
Reference: https://docs.brew.sh/Adding-Software-to-Homebrew

EDIT: looks like Homebrew [only accepts stable versioned formulae](https://docs.brew.sh/Acceptable-Formulae#stable-versions). Furthermore, [self-submitting formulae is frowned upon](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff).
