### ISSUE TITLE
Document glibc minimum version required

### ISSUE THREAD

**Issue by Magissia** [rigormorrtiss/discordo#306]
As is, the pre-built binary throws

./discordo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./discordo)
./discordo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./discordo)

If a specific glibc version is required, it needs to be specified somewhere.

**Comment by ayn2op** [comment]
5870e3e76447cf74ab4440d071bccfec8d810ca2 should fix the issue.
