### ISSUE TITLE
custom url parsing options?

### ISSUE THREAD

**Issue by aescolastico** [rigormorrtiss/discordo#321]
Is there existing functionality to modify what discordo considers a link? say in a config file?
for instance, this is a browser url that just opens the steam app sessions. 
`steam://joinlobby/1282100/109775244635338248/76561198398821476`
2nd question, what is the default way to copy a message to clipboard?

**Comment by aescolastico** [comment]
followup. when pressing random buttons i stumbled upon k, which seems to be able to copy the link i mentioned above. so theres already logic to recognize this kind of link. is there any way we could make it clickable with the "ctrl+click" feature?

**Comment by ayn2op** [comment]
Discordo does not recognize links, terminal does. To copy the content of the message to the clipboard, select the message and press `c` on your keyboard; make sure to install `xclip` or `wl-clipboard` before if you are using Linux.
