### ISSUE TITLE
Don't show deleted messages any longer

### ISSUE THREAD

**Issue by Ecorous** [rigormorrtiss/discordo#323]
Deleted messages currently show. This is very annoying

**Comment by ItsRedlyXD** [comment]
They should be colored red, and do something like Vencord's message logger (opt-in of course). Do you agree?

**Comment by Ecorous** [comment]
> They should be colored red, and do something like Vencord's message logger (opt-in of course). Do you agree?

Or, completely removed?

**Comment by rom4ster** [comment]
Nah show the deletions, super nice.

**Comment by ayn2op** [comment]
> They should be colored red, and do something like Vencord's message logger (opt-in of course). Do you agree?

This is a privacy concern. Someone using a client other than Discordo expects the message to be deleted; not to mention, this behavior also deviates from the official client.

Anyway, it should be fairly easy to implement this. Arikawa automatically updates the state when a message is deleted, so we just have to redraw all of the messages again when the `MESSAGE_DELETE` event is received.
