### ISSUE TITLE
What colour names does discordo support?

### ISSUE THREAD

**Issue by nevillepark** [rigormorrtiss/discordo#324]
Hi, when configuring discordo how should we specify colours? I tried the 8 ANSI colours but only some of them seemed to work.

**Comment by ayn2op** [comment]
W3C names and hex

List of color names supported: https://github.com/gdamore/tcell/blob/08c7757cd1c98810e46975da457c033dc8657ad8/color.go#L846

**Comment by nevillepark** [comment]
Thank you so much!
