### ISSUE TITLE
Malware found in Virus total scan?

### ISSUE THREAD

**Issue by Lahnshen** [rigormorrtiss/discordo#326]
https://www.virustotal.com/gui/file/f99571e9657c0f3b2a8b991ecb3b27b1a06b5afa39e2ba6d85d327150908c2f8?nocache=1
![image](https://github.com/ayn2op/discordo/assets/142650466/85136f3a-7bff-472b-a9a2-369d45acd111)
Is it still safe?

Tried with the Windows binary here:
https://nightly.link/ayn2op/discordo/workflows/ci/main

**Comment by ayn2op** [comment]
https://go.dev/doc/faq#virus
