### ISSUE TITLE
zsh: permission denied: discordo

### ISSUE THREAD

**Issue by jnptk** [rigormorrtiss/discordo#334]
Hey I just installed discordo, super exited to try it out and got this error message when trying to run it. `zsh: permission denied: discordo` can anyone help me with what is going on?

Thanks in advance.

**Comment by ghost** [comment]
`Permission denied` means that the permissions of the file dose not allow you to execute it.
You can change that using the command:
```
chmod +x discordo
```
to add the execute permission to the `discordo` binary.

**Comment by jnptk** [comment]
I thought so too. Also tried it with `sudo` but nothing changed, I still get the same error even after logging out and back in.

**Comment by ultimate-steve** [comment]
Could you paste the output of

`ls -l discordo` ?

**Comment by jnptk** [comment]
@ultimate-steve 
```
total 15072
drwxr-xr-x 2 xd xd     4096 Dec 22 17:52 cmd
-rwxr-xr-x 1 xd xd 15390460 Dec 22 17:58 discordo
drwxr-xr-x 2 xd xd     4096 Dec 22 17:52 docs
-rw-r--r-- 1 xd xd      979 Dec 22 17:52 go.mod
-rw-r--r-- 1 xd xd     8858 Dec 22 17:52 go.sum
drwxr-xr-x 7 xd xd     4096 Dec 22 17:52 internal
-rw-r--r-- 1 xd xd     1063 Dec 22 17:52 LICENSE
-rw-r--r-- 1 xd xd      359 Dec 22 17:52 main.go
-rw-r--r-- 1 xd xd     2573 Dec 22 17:52 README.md
```

BTW: I cannot do `ls -l discordo` I had to do `ls -l /usr/local/bin/discordo`

**Comment by ptonelli** [comment]
I believe you need to copy only the binary file discordo to /usr/local/bin, and not the complete directory

**Comment by ghost** [comment]
i think you may have copied the entire folder, meaning that the location of the executable is /usr/local/bin/discordo/discordo

you only need to move the discordo executable to /usr/local/bin, the rest of the folder is useless (after compilation that is)
the error is kinda misleading, cuz /usr/local/bin/discordo is a folder, and you can never execute folders

**Comment by jnptk** [comment]
jup that was it, thank you guys!
