### ISSUE TITLE
Extreme Screen Flashing

### ISSUE THREAD

**Issue by h2110100** [rigormorrtiss/discordo#335]
On Windows 23h3 terminal, screen starts flashing uncontrollably once logged in, can barely see anything, apparently its the messages loading. For every message loaded the screen refreshes, typing also causes the screen to refresh.

**Comment by ghost** [comment]
Looks like an issue in the [tview](https://github.com/rivo/tview) or [tcell](https://github.com/gdamore/tcell) libraries.
