### ISSUE TITLE
internal/config/config.go:5:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)

### ISSUE THREAD

**Issue by Kreijstal** [rigormorrtiss/discordo#336]
06:20:53 pi@juanraspberry discordo ±|main|→ go build .
go: downloading github.com/zalando/go-keyring v0.2.3
go: downloading github.com/diamondburned/arikawa/v3 v3.3.3
go: downloading github.com/rivo/tview v0.0.0-20231126152417-33a1d271f2b6
go: downloading github.com/godbus/dbus/v5 v5.1.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/time v0.5.0
go: downloading github.com/gorilla/websocket v1.5.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/gorilla/schema v1.2.1
go: downloading golang.org/x/net v0.19.0
go: downloading github.com/atotto/clipboard v0.1.4
go: downloading github.com/gdamore/tcell/v2 v2.6.0
go: downloading github.com/rivo/uniseg v0.4.4
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading golang.org/x/sys v0.15.0
go: downloading golang.org/x/text v0.14.0
go: downloading golang.org/x/term v0.15.0
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.15
internal/config/config.go:5:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
../../go/pkg/mod/github.com/mattn/go-runewidth@v0.0.15/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/pi/go/pkg/mod/github.com/rivo/uniseg@v0.4.4
../../go/pkg/mod/github.com/gdamore/tcell/v2@v2.6.0/nonblock_unix.go:23:2: found packages unix (affinity_linux.go) and main (mkasm.go) in /home/pi/go/pkg/mod/golang.org/x/sys@v0.15.0/unix
../../go/pkg/mod/golang.org/x/text@v0.14.0/encoding/encoding.go:19:2: import "golang.org/x/text/encoding/internal/identifier" is a program, not an importable package
package github.com/ayn2op/discordo
        imports github.com/ayn2op/discordo/cmd
        imports github.com/ayn2op/discordo/internal/ui
        imports github.com/gdamore/tcell/v2
        imports github.com/gdamore/encoding
        imports golang.org/x/text/encoding
        imports golang.org/x/text/encoding/internal/identifier
        imports golang.org/x/text/internal/gen
        imports golang.org/x/text/unicode/cldr
        imports golang.org/x/text/internal/gen: import cycle not allowed
../../go/pkg/mod/golang.org/x/text@v0.14.0/internal/gen/gen.go:38:2: found packages cldr (base.go) and main (makexml.go) in /home/pi/go/pkg/mod/golang.org/x/text@v0.14.0/unicode/cldr

**Comment by sewnie** [comment]
we are on go 1.21, you are on go 1.15.

**Comment by Kreijstal** [comment]
oh darn it, that is sad. raspbian wont update it probably
