### ISSUE TITLE
Support apt/PPA or dnf for Fedora

### ISSUE THREAD

**Issue by dnet890** [rigormorrtiss/discordo#337]
Hi
I use WSL. But, unfortunately WSL does not support ArchLinux officially and it is not perfect on Windows. So, I know you have Windows build. But, the thing is it does not support automatic update and the experience to enjoy the client via terminal is not really pleasant. Is it possible to support PPA/APT for Ubuntu or dnf for Fedora?

**Comment by sewnie** [comment]
Make it yourself :)
