### ISSUE TITLE
Documentation is Outdated/Nonexistent

### ISSUE THREAD

**Issue by gruelingpine185** [rigormorrtiss/discordo#341]
This is about the documentation for discordo. As far as I can tell through fiddling, documentation can be accessed via the following methods:
- `$ discordo -h`

```sh
discordo main ➜ discordo -h
Usage of discordo:
  -token string
    	The authentication token. (default "MTE2OTg0MzE2NDg3MDM1NzA0Mg.G8cDu1.63EB2HSLo1uxM0jGr8_h4W8Ppgf9l8-XNPziSE")
```
- `$ man ./docs/discordo.1` (from within cloned repo)

<img width="1219" alt="Screenshot 2024-02-02 at 5 01 57 PM" src="https://github.com/ayn2op/discordo/assets/66073333/83ac0098-c0a9-4110-9896-c591ed00ae56">

- And the markdown files in `./docs/`

Of these, the most detailed and useful one is the manpage. It gives us an idea that there are keybindings for the program, where the discordo expects the configuration file to be, and the available arguments/flags. The issue lays in the fact that it is outdated. For example, The keybinding for toggling the guilds tree as per the manpage is `Alt + b` where in reality it is `Ctrl + b`. There are other things, but the point remains unfazed. 

Also there is ~~no default/example config file.~~ Actually, I stand corrected. The default (I presume) is at `./internal/config/config.yml`. However, this should at least be recognized in`./docs/` or a have an example config there that we can look at without having to dig through source code. 

I'm on MacOS btw.

**Comment by gruelingpine185** [comment]
The manpage doesn't have to be as thorough and git's, but if there is any single place where all the bits and pieces of information regarding documentation that have been scattered around this repo should reside, my vote is on the manpage.

**Comment by Mox4572** [comment]
MacOS doesn’t pass alt to the command line last I checked

**Comment by gruelingpine185** [comment]
You can still send characters like áé¡¿ and some Greek ones also from  inside the terminal. You can use alt + key or alt + shift + key.

I don't think it sends Mets keys to the terminal tho. Meta key bindings are used to manipulate the app or system itself.

**Comment by cyberme0w** [comment]
Just to document what I've read until now in the Discord chat, the reasoning behind removing the man page is because it is not available on every platform that Discordo supports. A properly maintained "discordo --help" seems to be the way to go instead.

**Comment by ayn2op** [comment]
A sample configuration is now in the configuration section of README.md
