### ISSUE TITLE
Skin-tone chars are not wiped when changing channels

### ISSUE THREAD

**Issue by cyberme0w** [rigormorrtiss/discordo#343]
Hi there! First of all, thank you for working on such a cool project. I've been using it for the last couple of days on a GUI-less system and it's been a neat experience.

I would like to report what I think might be a bug related to displaying toned emojis. I haven't taken a look into how exactly discordo works to try and fix it, but I thought I'd at least mention it here in an issue first.

Briefly put, when changing from channel A to channel B, if there were any toned emoji, the :skin-tone-*: char is not wiped if channel B does not have enough text (e.g. it's empty).

---

**Steps to reproduce:**
1. Create a new server/guild with two text channels (and make sure it's visible in discordo - see #287)
2. Write a message with a toned emoji in one channel
3. Swap to the other channel, which should still be empty

**Expected result:**
Second channel is empty and the message_text window should be empty.

**Actual result:**
Second channel wrongly displays the :skin-tone-*: emojis.

---

I've also taken two screenshots that illustrate the issue. For what it's worth, the toned emoji is `:ok_hand::skin-tone-1:`.

**Screenshot of step 2:**
![2024-02-15-164709_1039x431_scrot](https://github.com/ayn2op/discordo/assets/59916540/832ad50e-8012-42e8-bca0-7c953030e31c)

**Screenshot of step 3:**
![2024-02-15-164715_1039x431_scrot](https://github.com/ayn2op/discordo/assets/59916540/e2bebca7-8829-4a26-aac4-1a4dde2ac910)

Please let me know if there's any more information I can provide to help debug this.

Cheers!
cyberme0w

**Comment by sewnie** [comment]
This is an issue with tview

**Comment by cyberme0w** [comment]
Looks like you're right. I also realized the xfce4-terminal simply doesn't support those combined chars (my bad, should have checked that first). Kitty on the other side has no issue and both displays them in the correct color, as well as wipes them properly when swapping channels.

**Comment by ayn2op** [comment]
Related, maybe? https://github.com/gdamore/tcell/issues/679
