### ISSUE TITLE
Login keyring unlock asking for unknown password?

### ISSUE THREAD

**Issue by pawamoy** [rigormorrtiss/discordo#345]
When I run `discordo`, it asks for a password.

![keyring](https://github.com/ayn2op/discordo/assets/3999221/4a4c75fd-cde6-4f74-ac5a-42d4acaced97)

No password that I know of works. Not my login password, not my sudo password, not my GPG password. What password am I suppose to enter here? Am I lacking some system software?

I tried running `sudo -E discordo` first: it doesn't ask to unlock and goes straight to the TUI login form. I login, checking "remember me", but next time I call `discordo`, it asks again to unlock the keyring and I have to fill the login form again.

Could it be related to https://github.com/ayn2op/discordo/issues/286?

Note that when other applications ask me to unlock the default keyring, I can type my sudo password and it works fine.

I'm on ArchLinux. Installed discordo from AUR: https://aur.archlinux.org/packages/discordo-git

**Comment by ayn2op** [comment]
What DE/WM are you using? What keyring software do you have installed?

**Comment by pawamoy** [comment]
Thanks for your help! I'm running Qtile, a tiling wm written in Python. No particular desktop environment. I have gnome-keyring-daemon and polkit-gnome-authentication-agent-1 :shrug:

**Comment by pawamoy** [comment]
On another system, I don't have auto-login enabled, so the default keyring is unlocked when I log in, and discordo does not ask me for the password :+1: However I'm getting an error message: `token not found in keyring: secret not found in keyring`. Discordo works fine on the other system after I hit cancel on the keyring unlock popup :joy: 

So in one case, it asks to unlock, but works fine if I cancel, and in the other case, it doesn't ask to unlock, but fails with a "not found" error.

**Comment by ayn2op** [comment]
To use automatic unlocking with automatic login, you can set a blank password for the default keyring. Note that the contents of the keyring are stored unencrypted in this case.
Alternatively, if using GDM and LUKS, GDM can unlock your keyring if it matches your LUKS password. For this to work, you need to use the [systemd init in your mkinitcpio.conf](https://wiki.archlinux.org/title/Mkinitcpio#Common_hooks) as well as the [appropriate kernel parameters](https://wiki.archlinux.org/title/Dm-crypt/System_configuration#Using_systemd-cryptsetup-generator). See [[1]](https://reddit.com/r/Fedora/comments/jwnqq5/) for more details. Read more about [PAM here](https://wiki.gnome.org/Projects/GnomeKeyring/Pam). To disable the password prompt, take a look at [how to disable it](https://askubuntu.com/a/875).
