### ISSUE TITLE
possibility to **not** use a keyring?

### ISSUE THREAD

**Issue by formula-spectre** [rigormorrtiss/discordo#351]
i'm using discordo, and i've noticed that it stores the auth in a keyring. problem: I don't have and want one.  
is there a way to store it somewhere in ~/.local/ in an encrypted way without using a keyring? if not, what's the dumbest smallest keyring I can use only for discordo?

**Comment by sewnie** [comment]
#286

**Comment by ayn2op** [comment]
> i'm using discordo, and i've noticed that it stores the auth in a keyring. problem: I don't have and want one. is there a way to store it somewhere in ~/.local/ in an encrypted way without using a keyring? if not, what's the dumbest smallest keyring I can use only for discordo?

If you don't care about your authentication token, just alias `discordo` as `discordo --token "YOUR_TOKEN_HERE"` in your shell profile.

**Comment by formula-spectre** [comment]
but the token is stored in the keyring no? or you mean the one that I have to get in the web app with dev tools?

**Comment by ayn2op** [comment]
> but the token is stored in the keyring no? or you mean the one that I have to get in the web app with dev tools?

Yes. You have to manually get the token and alias `discordo` as `discordo --token "TOKEN_FROM_DEVTOOLS"`:

```sh
alias discordo=discordo --token "..."
```

**Comment by formula-spectre** [comment]
i see, thanks
