### ISSUE TITLE
Unable to launch in rootless podman

### ISSUE THREAD

**Issue by PipeItToDevNull** [rigormorrtiss/discordo#360]
Running discordo in an alpine container in rootless podman results in an exit with 

```
token not found in keyring: exec: "dbus-launch": executable file not found in $PATH
```

I am investigating a bit still as well 

--- 

Adding `dbus-x11 gnome-keyring` packages gets further, to 

```
token not found in keyring: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'
```

**Comment by PipeItToDevNull** [comment]
The furthest I can get is with the following 

```
dbus-launch -- sh
gnome-keyring-daemon --unlock
gnome-keyring-daemon --start
discordo 
2024/03/06 22:23:54 token not found in keyring: failed to unlock correct collection '/org/freedesktop/secrets/collection/login'
```

---

Little bit more progress 

```
/ # eval "$(dbus-launch --sh-syntax)"
/ # cd 
~ # mkdir -p ~/.cache
~ # mkdir -p ~/.local/share/keyrings
~ # ls .local/share/keyrings/
~ # eval "$(printf '\n' | gnome-keyring-daemon --unlock)"
~ # eval "$(printf '\n' | /usr/bin/gnome-keyring-daemon --start)"
~ # discordo 
2024/03/06 22:28:13 token not found in keyring: secret not found in keyring
```

**Comment by PipeItToDevNull** [comment]
Ok, so this seems to work when using a token, despite the error. But a login does not

**Comment by ayn2op** [comment]
Create a new keyring named "login" and try again.

**Comment by PipeItToDevNull** [comment]
If you have any clue how to do that, I am all ears. Documentation on keychains is almost entirely graphical

**Comment by PipeItToDevNull** [comment]
A login keyring appears to be created by default when using the above 

```
ls ~/.local/share/keyrings/
login.keyring  user.keystore
```

**Comment by PipeItToDevNull** [comment]
So actually, without any of this keyring stuff, I can login just fine with a token but not a login

**Comment by ayn2op** [comment]
> The furthest I can get is with the following
> 
> ```
> dbus-launch -- sh
> gnome-keyring-daemon --unlock
> gnome-keyring-daemon --start
> discordo 
> 2024/03/06 22:23:54 token not found in keyring: failed to unlock correct collection '/org/freedesktop/secrets/collection/login'
> ```
> 
> Little bit more progress
> 
> ```
> / # eval "$(dbus-launch --sh-syntax)"
> / # cd 
> ~ # mkdir -p ~/.cache
> ~ # mkdir -p ~/.local/share/keyrings
> ~ # ls .local/share/keyrings/
> ~ # eval "$(printf '\n' | gnome-keyring-daemon --unlock)"
> ~ # eval "$(printf '\n' | /usr/bin/gnome-keyring-daemon --start)"
> ~ # discordo 
> 2024/03/06 22:28:13 token not found in keyring: secret not found in keyring
> ```

"token not found in keying: secret not found in keyring" is for debugging purposes, you should see the login screen if the token does not exist in the keyring.

**Comment by PipeItToDevNull** [comment]
This could have been me being stupid, I think the method of pasting passwords maybe. but it works now with a login and none of this keyring stuff so that is good enough for me 

Thank you for your time and patience
