### ISSUE TITLE
Timestamps don't show in local time

### ISSUE THREAD

**Issue by 10kmotorola** [rigormorrtiss/discordo#361]
Date is set correctly on my system:
```
$ date
Fri Mar  8 12:24:46 PM EST 2024
```
Yet timestamps are in UTC. I'm using Hyprland fwiw.

**Comment by cyberme0w** [comment]
Looks like something where
https://pkg.go.dev/time#ParseInLocation and https://pkg.go.dev/time#Location would help.

Edit: also somewhat related, the timestamps are always time-only, even for messages older than a day, which is a bit confusing. It'd be nice to be able to see the date too for those older messages.
