### ISSUE TITLE
Duplicate channels on return from Suspend / Discordo does not automatically update currently selected channel?

### ISSUE THREAD

**Issue by dagleykd** [rigormorrtiss/discordo#370]
Little bug report - Just noticed today that if I put my laptop (running MX Linux) to sleep with Discordo running (I run it through the XFCE or cool-retro-term Terminals)...when I wake it up, it lists duplicates of the channels I am connected to (see attached pic) until I close and restart:
![Screenshot_2024-03-18_20-27-12](https://github.com/ayn2op/discordo/assets/20607462/5ddef2b3-226d-4213-bf23-062754b5ce43)

This seems to stack as well - if I still leave Discord running with the duplicates and put the computer to sleep again...wait a few minutes...and wake it up, there will then be THREE duplicates of the channels...?

Also, when waking from Suspend, Discordo doesn't consistently automatically update the channel I have selected - I have to select another different channel and then switch back before it seemingly catches up on messages?

Thanks though! Very cool piece of software - so much lighter on resources than Discord proper for those of us who most just bang out messages on our keyboards rather than using things like Voice/Video! :)

**Comment by epetousis** [comment]
I think the first issue may be a result of the (very nice) changes in #369. I wasn't noticing them before.

**Comment by dagleykd** [comment]
@ayn2op @epetousis Just a note that the previous version of Discordo I was using had been downloaded in January. I downloaded the most recent 'nightly' pre-built and am still getting the same channel dupe bug?

Assuming it's not been fixed in a build yet?

Thanks for the quick replies and efforts! :)
