### ISSUE TITLE
*Feature Request* Time/Date Stamps on messages?

### ISSUE THREAD

**Issue by dagleykd** [rigormorrtiss/discordo#380]
Any chance we could get time/date stamps added to messages? :)

**Comment by ayn2op** [comment]
[Set `timestamps` to `true`](https://github.com/ayn2op/discordo?tab=readme-ov-file#configuration)

**Comment by dagleykd** [comment]
> [Set `timestamps` to `true`](https://github.com/ayn2op/discordo?tab=readme-ov-file#configuration)

Oh thanks - my apologies - I didn't know there was a config file!

I just found mine (on MX Linux) at /home/,config/discordo/config.yml

I've made changes to it, but when I open Discordo, the changes don't appear to have taken?

**Comment by ayn2op** [comment]
> > [Set `timestamps` to `true`](https://github.com/ayn2op/discordo?tab=readme-ov-file#configuration)
> 
> Oh thanks - my apologies - I didn't know there was a config file!
> 
> I just found mine (on MX Linux) at /home/,config/discordo/config.yml
> 
> I've made changes to it, but when I open Discordo, the changes don't appear to have taken?

The extension is incorrect. The correct extension is `toml`.

**Comment by dagleykd** [comment]
> > > [Set `timestamps` to `true`](https://github.com/ayn2op/discordo?tab=readme-ov-file#configuration)
> > 
> > 
> > Oh thanks - my apologies - I didn't know there was a config file!
> > I just found mine (on MX Linux) at /home/,config/discordo/config.yml
> > I've made changes to it, but when I open Discordo, the changes don't appear to have taken?
> 
> The extension is incorrect. The correct extension is `toml`.

Mine literally says yml though and was autogenerated? I didn't create the config file, I just went with the extension that was already there? Is that a bug then?

**EDIT - just tried changing the extension to toml and the program immediately crashes on launch...? Changed it back to yml and it works again...? This is with the most recent nightly pre-build.**
![Screenshot_2024-04-03_19-18-35](https://github.com/ayn2op/discordo/assets/20607462/d55260d5-75b2-4497-aa62-6f02482bf180)

This thread also mentions the config file as being a yml?
https://github.com/ayn2op/discordo/issues/331

**Comment by ayn2op** [comment]
> **EDIT - just tried changing the extension to toml and the program immediately crashes on launch...? Changed it back to yml and it works again...? This is with the most recent nightly pre-build.**

Are you building from source? The newer versions use TOML, not YAML. You are most likely on an older version. The file is no longer generated on startup in newer versions and TOML is used as configuration format instead of YAML.

**Comment by dagleykd** [comment]
> > **EDIT - just tried changing the extension to toml and the program immediately crashes on launch...? Changed it back to yml and it works again...? This is with the most recent nightly pre-build.**
> 
> Are you building from source? The newer versions use TOML, not YAML. You are most likely on an older version.

I am not building from source - I'm downloading the latest pre-built 'nightly' - or is that massively out of date somehow...?

**Comment by ayn2op** [comment]
> I am not building from source - I'm downloading the latest pre-built 'nightly' - or is that massively out of date somehow...?

Weird. The prebuilt binaries are built from the `main` branch. Try building it from source.

**Comment by dagleykd** [comment]
> > I am not building from source - I'm downloading the latest pre-built 'nightly' - or is that massively out of date somehow...?
> 
> Weird. The prebuilt binaries are built from the `main` branch.

Odd....let me try deleting the yml temporarily to see if the program still launches (it doesn't when I rename it to toml

**Comment by dagleykd** [comment]
OK - tried deleting the yml and launching the program and it launched fine...didn't even ask me to log in again.

Will try copy-pasting the example config file and placing it with toml extension in the .config folder and see if it launches then.

**Comment by dagleykd** [comment]
**That did it! :)**

Deleting the yml file, and copy-pasting a fresh config from the main page and then saving it as config.toml to the .config/Discordo folder seems to have worked and my config changes are working now. Very strange! Maybe my old pre-built way back when I first got Discordo was from long enough ago it used yml and then when I downloaded more recent builds they were the toml builds and somehow that yml file was just leftover?

**Comment by dagleykd** [comment]
Pardon the quick n00b question - programming and vi / vim isn't my forte. Looking at the keybindings in the config file, what key is 'Rune' referring to? For example, the 'select reply' binding is 'Rune[s]' ...?

**Comment by ayn2op** [comment]
> Pardon the quick n00b question - programming and vi / vim isn't my forte. Looking at the keybindings in the config file, what key is 'Rune' referring to? For example, the 'select reply' binding is 'Rune[s]' ...?

Rune just means character, so `Rune[s]` is the `s` key, `Rune[k]` is the `k` key, so on.

**Comment by dagleykd** [comment]
> > Pardon the quick n00b question - programming and vi / vim isn't my forte. Looking at the keybindings in the config file, what key is 'Rune' referring to? For example, the 'select reply' binding is 'Rune[s]' ...?
> 
> Rune just means character, so `Rune[s]` is the `s` key, `Rune[k]` is the `k` key, so on.

Ah, thanks so much mate, pardon my ignorance! :) Many thanks for all the hard work on this awesome program, and also the prompt replies!
