### ISSUE TITLE
Feature Request: view image

### ISSUE THREAD

**Issue by toyteal** [rigormorrtiss/discordo#382]
addition of an image display feature will be cool and

**Comment by Kanken6174** [comment]
It seems like this feature existed at some point but i've got no idea how you're supposed to use it... the files related to the PR that was implementing this feature seem gone as well?

**Comment by Kanken6174** [comment]
apparently it's supposed to be this:
open = "Rune[o]"

i'd guess the run key is the win key but this doesn't work for me (kitty terminal)

**Comment by Kanken6174** [comment]
func defaultKeys() Keys {
	return Keys{
		FocusGuildsTree:   "Ctrl+G",
		FocusMessagesText: "Ctrl+T",
		FocusMessageInput: "Ctrl+P",
		ToggleGuildsTree:  "Ctrl+B",

		SelectPrevious: "Rune[k]",
		SelectNext:     "Rune[j]",
		SelectFirst:    "Rune[g]",
		SelectLast:     "Rune[G]",

		GuildsTree: GuildsTreeKeys{
			SelectCurrent: "Enter",
		},

		MessagesText: MessagesTextKeys{
			SelectReply: "Rune[s]",

			Reply:        "Rune[r]",
			ReplyMention: "Rune[R]",

			Delete: "Rune[d]",
			Yank:   "Rune[y]",
			Open:   "Rune[o]",
		},

		MessageInput: MessageInputKeys{
			Send:   "Enter",
			Editor: "Ctrl+E",
			Cancel: "Esc",
		},
	}
}

apparentfly rune[o] does it by default, but o doesn't work for me hmm... rune is a go thing so it shouldn't matter here

**Comment by Kanken6174** [comment]
So apparently you're supposed to use j/k to select the message (clicking on it doesn't work for me) and then use o to open the contents through the os's standard handler, which for me is my web browser... kinda annoying it's not built it hmm
