### ISSUE TITLE
Can an exit key other than <ctr-c> be added?

### ISSUE THREAD

**Issue by themarcman314** [rigormorrtiss/discordo#386]

**Comment by dagleykd** [comment]
@themarcman314 Just tried this on MX Linux running Discordo through the XFCE and cool-retro-term Terminals and Alt-F4 works on both...?

**Comment by themarcman314** [comment]
Is there any way to rebind this to q?

**Comment by ayn2op** [comment]
If someone wants to work on this, feel free to do so.

Related: <https://github.com/rivo/tview/blob/master/application.go#L153>

**Comment by strizhkindenis** [comment]
Tried doing this 
https://github.com/ayn2op/discordo/pull/405
