### ISSUE TITLE
Feature Request: Loaded Images in Chats

### ISSUE THREAD

**Issue by Qwertyto** [rigormorrtiss/discordo#388]
So far, if I were to open up a channel in any server with images posted, the images are simply shown as links. would it possible to have the images load in the teminal with the link above, or would that break the whole point of using a terminal client? Great program otherwise!
![Feature rq terminal discord meme channel](https://github.com/ayn2op/discordo/assets/126300320/c1ac6e5d-2487-4bac-9332-69836504ca9f)

**Comment by ayn2op** [comment]
You can focus the messages text widget with `Ctrl+T`, select a message using `j` and `k` keys, and press `o` to open the attachments in the OS default browser.

**Comment by HelmicNewciv** [comment]
Was looking to see if this had inline image support (ie in kitty or wezterm), since my main reason for wanting a TUI discord client is being able to navigate everything through the keyboard for pain management reasons rather than a distaste for images.
