### ISSUE TITLE
Feature Request: Abiity to change the text color of chat messages / channel (and friend) titles

### ISSUE THREAD

**Issue by dagleykd** [rigormorrtiss/discordo#389]
Hi all,

I may be blind, but I don't see a way to edit the text color of chat messages and server/DM titles in the config file? I see you can change the color of the server/DM heading (Guilds), and the author color and border color, but I don't see an option for chat text, server/DM text list color, or for the highlight color of a selected channel?

On my laptop, the channel I have selected gets highlighted, but is highlighted in white and the text is white, so it completely blends in and you can't read what channel you are viewing (see attached screenshot).

Should be a fairly easy feature to add to allow customizable colors for those? :)

Cheers and again, thanks for the hard work....great little program! :)
![Screenshot_2024-04-22_14-12-18](https://github.com/ayn2op/discordo/assets/20607462/f4019074-8e8b-46bb-9a3b-3d284c6c6ed8)

**Comment by youngkaneda** [comment]
I can relate with that, have the same problem, having the colors customizable would be awesome

**Comment by emanueljg** [comment]
+1. Sounds like a great first pull request.

**Comment by ayn2op** [comment]
If anyone wants to open a pull request, feel free to do so.

**Comment by DaniyalAhmadSE** [comment]
It would be really nice to have that option.
