### ISSUE TITLE
Can't copy, but has xclip installed

### ISSUE THREAD

**Issue by youngkaneda** [rigormorrtiss/discordo#391]
Hello on my setup with arch linux I can not copy the messages using the keybind, I already has xclip installed, there are any type of logs that discordo produces? I could not found at all. I'm using kitty as the terminal emulator.

**Comment by ayn2op** [comment]
Are you using Wayland? If yes, you need to install `wl-clipboard`.

**Comment by youngkaneda** [comment]
Actually I'm using X11

**Comment by youngkaneda** [comment]
For some reason after reinstalling, it worked again, closing
