### ISSUE TITLE
Feature Request: encrypted tokens

### ISSUE THREAD

**Issue by HalanoSiblee** [rigormorrtiss/discordo#394]
Store user discord tokens into $HOME /.config/discordo _encrypted_
that will lead to faster and safer method and launch directly into discord
simply implement discordo --store "token" should do the job.
the decryption key should be randomized at compile time.

**Comment by ayn2op** [comment]
Where would the decryption key be stored? Hard-coded?

**Comment by HalanoSiblee** [comment]
decryption key should be inside the binary and get randomized during the compile time
or try another method like this one :
fetch the system like [ HWID distro-name cpu-cores host-name user-name ]
after that mix all them together and generate sha256 decryption key
should be different on each user who use discordo.

**Comment by HalanoSiblee** [comment]
```go
// Halano Is Coding ᕙ(⇀‸↼‶)ᕗ
package main

import (
        "fmt"
        "os"
        "crypto/sha256"
        "encoding/hex"
)

func main() {
        machineIDFile := "/etc/machine-id"
        data, err := os.ReadFile(machineIDFile)
        if err != nil {
                fmt.Println("Error reading machine ID:", err)
                return
        }
        hwidBytes := []byte(data)
        hash := sha256.Sum256(hwidBytes)
        hashStr := hex.EncodeToString(hash[:])
        fmt.Println(hashStr)
}

```

**Comment by HalanoSiblee** [comment]
I find another excellent method using sqlite3 + crypto to encrypt tokens locally & safely
used in great opensource project like [gomuks](https://github.com/tulir/gomuks) and [iamb](https://github.com/ulyssa/iamb)
