### ISSUE TITLE
Opens to Black Screen

### ISSUE THREAD

**Issue by Reynbow** [rigormorrtiss/discordo#397]
When I first opened it, I opened it to a login screen.
Then I got distracted with something else, closed it and am now trying to re-open it and it just opens to a black screen only.
![image](https://github.com/ayn2op/discordo/assets/19285509/16be11a7-d81a-4d14-ab44-1e7561b53424)

> tried the standalone .exe
> tried building it myself
> tried deleting discordo folder in localappdata

Nothing, just a black screen

**Comment by ayn2op** [comment]
Run the executable again and send the contents of the log file here.

**Comment by Reynbow** [comment]
> Run the executable again and send the contents of the log file here.

where is the log file? I'm not seeing any log file created alongside the .exe

**Comment by ayn2op** [comment]
It is located at `%LocalAppData%/discordo` on Windows.

**Comment by Reynbow** [comment]
oop - thanks, this helped me resolve the issue
was using the wrong shortcut, had a shortcut with my token, which I thought I was using, and another without my token
