### ISSUE TITLE
Is development still continuing?

### ISSUE THREAD

**Issue by dagleykd** [rigormorrtiss/discordo#398]
Not an issue, but just a quick question - I really enjoy Discordo but see that there has been very little development on it for the last 2 months...

Just curious if it is still being developed...?

Thanks! :)

**Comment by ghost** [comment]
not really.

something as simple as unread channel indicators are yet to be implemented.

a lot of login errors

and the original owner lost most of his hope

**Comment by ayn2op** [comment]
Yes, but Discord API for user accounts is very difficult to work with, things change very quickly and there is no way to keep track without documentation which Discord does not provide since user accounts are against ToS.
