### ISSUE TITLE
Does not open if the saved login account is suspended

### ISSUE THREAD

**Issue by threwawaythisaccount** [rigormorrtiss/discordo#399]
![image](https://github.com/ayn2op/discordo/assets/138542238/e8de6d6b-3ab7-4e8d-af85-89fe2f39c1c8)
![image](https://github.com/ayn2op/discordo/assets/138542238/609afd43-e254-465d-a7dc-9633853240fc)

(And for some people that would probably go off topic, No, I did not get suspended for doing any illegal stuff. I simply jokingly said I was 12 and Discord took it seriously.)

**Comment by threwawaythisaccount** [comment]
Oh I forgot to mention, it is easily fixed by removing this
![image](https://github.com/ayn2op/discordo/assets/138542238/efcecc6d-41ff-4cf7-a9c0-ff8f5d39d827)
But I think showing an error or something would be nice, instead of not printing anything in the terminal

**Comment by ayn2op** [comment]
> Oh I forgot to mention, it is easily fixed by removing this ![image](https://private-user-images.githubusercontent.com/138542238/336351375-efcecc6d-41ff-4cf7-a9c0-ff8f5d39d827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTgzMDMsIm5iZiI6MTcxNzYxODAwMywicGF0aCI6Ii8xMzg1NDIyMzgvMzM2MzUxMzc1LWVmY2VjYzZkLTQxZmYtNGNmNy1hOWMwLWZmOGY1ZDM5ZDgyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQyMDA2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTc0NWZiNWY4NGUwZGY0ZGE2ZDYxMTFhZTI0MTBhNzMzYWVkMTQ2MzY0NDhhZWFjZTVhNjMzNDQ2OGY2YjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c6yi6JwOS6WdHMWW1taarop99qISDQ8UrILu2osfZrw) But I think showing an error or something would be nice, instead of not printing anything in the terminal

It does write "4004 Authentication failed" to the log file.
