### ISSUE TITLE
Missing font?

### ISSUE THREAD

**Issue by critamine** [rigormorrtiss/discordo#40]
Hi,

First off. I love this project immensely. Thank you for developing it!

I have a very minor issue I'd like to report, it is likely something missing on my end or how I have my terminal configured. I see on your sceenshot that the selected box has a slightly thicker border than the others. However, when I select a field, I am given what I believe to be the "missing font" error box or something. I've seen this before when using emojis without the proper font installed. See below:

![image](https://user-images.githubusercontent.com/67632697/132249571-cbbb64b5-40f8-4021-915e-37a15de90685.png)

Any idea what I'm missing? I appreciate it! I'll likely do some digging myself when I have time tomorrow. Cheers.

**Comment by rigormorrtiss** [comment]
The "thicker" borders are just Unicode characters (`\u2550`, `\u2551`, `\u2554`, `\u2557`, `\u255a`, `\u255d`) that are used alternatively when the InputField is focused for distinction; it is very likely that the font you are using in the terminal may not support them which is causing this issue. May I know which font you are using in the terminal emulator? Additional information such as which terminal emulator and OS you are using may be helpful as well.

**Comment by rigormorrtiss** [comment]
For now, I am closing this issue, feel free to reopen it if the issue persists.
