### ISSUE TITLE
How to logout

### ISSUE THREAD

**Issue by 0verread** [rigormorrtiss/discordo#406]
I could not find any keybinding information or a way to logout. Also, not sure how to clear the state so I can fresh login.

**Comment by ml21** [comment]
ctrl+c

**Comment by ayn2op** [comment]
Currently, the only way to log out is to remove the token entry from the keyring.

**Comment by ayn2op** [comment]
You can use [`jaraco/keyring`](https://github.com/jaraco/keyring#command-line-utility) CLI to delete the `discordo` entry from the keyring:
```sh
keyring del discordo token
```
