### ISSUE TITLE
Wrong reply

### ISSUE THREAD

**Issue by BrokeTb** [rigormorrtiss/discordo#407]
When I hit r to reply after selecting, as the chat moves it replies the next message or to the next number of message defined by how many new messages have been send. Basically, reply isnt stable please look into this, thanks!.

**Comment by ingenarel** [comment]
was gonna pull an issue about this a long time ago but didn't because i was lazy. a few minutes ago this was being a pain in the ass and lo and behold there's already an issue about this lol.
