### ISSUE TITLE
What is Rune[key] and how to add custom shortcut ?

### ISSUE THREAD

**Issue by GunGunGun** [rigormorrtiss/discordo#408]
```
[keys]
focus_guilds_tree = "Ctrl+G"
focus_messages_text = "Ctrl+T"
focus_message_input = "Ctrl+P"
toggle_guild_tree = "Ctrl+B"
select_previous = "Rune[k]"
select_next = "Rune[j]"
select_first = "Rune[g]"
select_last = "Rune[G]"
copy_selected_message = "Ctrl+F"
```

I tried to add key to copy selected message, I pressed Ctrl+F and nothing happens.

And I don't know how to use Rune ?

Did I do anything wrong ? I'm using Lubuntu LTS.

**Comment by ayn2op** [comment]
From [`tcell.KeyRune`](https://github.com/gdamore/tcell/blob/d1364d5937eed5d5ac03b4fec309beb6db26f3eb/key.go#L284):
>  KeyRune is special however, in that it is a place holder key indicating that a printable character was sent.  The actual value of the rune will be transported in the Rune of the associated EventKey.

To put it simple, `Rune[x]` just means character `x`. For instance, `Rune[j]` just means character `j`. Furthermore, to override the default keybinding to copy the selected message, you can modify the `keys.messages_text.yank` value:
```toml
[keys.messages_text]
yank = "Ctrl+F" # default: Rune[y]
```

The [`DefaultConfig` function](https://github.com/ayn2op/discordo/blob/affce8159cda2ed571305077fd06e5e81f917308/internal/config/config.go#L27) in the `config` package (located in the `internal` directory) contains all of the default keybindings.

**Comment by ayn2op** [comment]
To override the default keybinding to copy the selected message, you can modify the `keys.messages_text.yank` value:
```toml
[keys.messages_text]
yank = "Ctrl+F" # default: Rune[y]
```
