### ISSUE TITLE
[QUESTION] Image support

### ISSUE THREAD

**Issue by crispy-caesus** [rigormorrtiss/discordo#412]
I've read some issues about image support being added, but also not there anymore?
I've added `show_image = "Rune[i]" ` to my config but it doesn't seem to do anything. Is opening it in external programs the only way right now or is there another?

**Comment by ayn2op** [comment]
The `show_image` keybinding no longer exists in the recent versions. Currently, Discordo opens the attachments of the selected message in the default application when the `messages_text.open` keybinding is pressed (default: `Rune[o]`).

**Comment by crispy-caesus** [comment]
alright, thanks for clarification :D, wonderful project, thanks for all the work
