### ISSUE TITLE
Secrets Service problem, discordo cant login

### ISSUE THREAD

**Issue by yuzi233** [rigormorrtiss/discordo#413]
My pc is a VPS with out GPU, no desktop envirment installed, a debian linux. 
After the build , my first run crash say  "failed to get token from keyring: The name org.freedesktop.secrets was not provided by any .service files" then I try install some apps(like keepassxc, keyringer), until Installed the gnome-keyring, it still crash, but message changed, it say"failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'". I try to run "ls /", but no "org" folder found, then I try to run as root "sudo discordo", it say dbus-luanch not found. well I search for it, and try "sudo apt install dbus-x11" to install dbus-x11 
and it  crash say"failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'"  again. i try install xfc4 and reboot , but nothing change.
 I dont know how deal with it.

**Comment by ayn2op** [comment]
You need to unlock the default collection. Run `gnome-keyring-daemon --unlock` to unlock it.

**Comment by yuzi233** [comment]
nothing respond, I run gnome-keyring-daemon --unlock , type the password, and nothing respond

**Comment by yuzi233** [comment]
> nothing respond, I run gnome-keyring-daemon --unlock , type the password, and nothing respond

what discordo required? I will reinstall the debian, try again

**Comment by ayn2op** [comment]
> nothing respond, I run gnome-keyring-daemon --unlock , type the password, and nothing respond

Could you elaborate please? What do you mean by "nothing respond"? Unlock the default keyring and run the program again; if the issue still persists, check the log file located in the `~/.cache/discordo` directory. Follow [these instructions](https://github.com/jaraco/keyring/blob/main/README.rst#using-keyring-on-headless-linux-systems) step-by-step to unlock the keyring.

**Comment by hustlerone** [comment]
> > nothing respond, I run gnome-keyring-daemon --unlock , type the password, and nothing respond
> 
> Could you elaborate please? What do you mean by "nothing respond"? Unlock the default keyring and run the program again; if the issue still persists, check the log file located in the `~/.cache/discordo` directory. Follow [these instructions](https://github.com/jaraco/keyring/blob/main/README.rst#using-keyring-on-headless-linux-systems) step-by-step to unlock the keyring.

it hangs

**Comment by ayn2op** [comment]
Related: https://github.com/zalando/go-keyring/issues/116

**Comment by hustlerone** [comment]
You shouldn't close this issue since it's still an issue, even if it's mostly out of your control

**Comment by yuzi233** [comment]
I give up, because my english not good either
