### ISSUE TITLE
option to use proxy

### ISSUE THREAD

**Issue by dinamycam** [rigormorrtiss/discordo#439]
hello and thanks for the project.
is there any way to pass proxy options to the app,
and what about support for socks5, http/s formats?

**Comment by ayn2op** [comment]
Thank you for taking the time to share this suggestion and for your interest in Discordo! At this time, we do not plan to support proxies as it is beyond the current scope of this project. However, you can still achieve similar functionality by using a system-wide proxy or configuring proxies at the network level. Check out [proxychains](https://github.com/haad/proxychains) for Linux and [Proxifier](https://www.proxifier.com) for Windows and macOS.
