### ISSUE TITLE
found some issues binding a few keys.

### ISSUE THREAD

**Issue by ingenarel** [rigormorrtiss/discordo#446]
ctrl+C -> is used to quit the prgram, you can remap quit, but cannot assign anything else to it, possibly because it's used to terminate some programs
ctrl+H -> can't assign anything to it, quite possible because it gets inputted as backspace
ctrl+I -> can't assign anything to it, quite possibly because it gets inputted as tab
ctrl+L -> can't assign anything to it, quite possibly because it gets inputted as the enter key
ctrl+V -> is bindable, but on the windows terminal, unbind the ctrl+v key

the last one isn't an issue actually, but i've found the others interesting. i don't think this is much of an issue, but also, terminal tools like (neo)vi(m) can register those as keybinds, so i think it is possible to bind these keys somehow.

**Comment by ayn2op** [comment]
Related:
- https://github.com/gdamore/tcell/issues/204
- https://github.com/gdamore/tcell/issues/495
- https://github.com/gdamore/tcell/issues/258
- https://github.com/gdamore/tcell/issues/671
