### ISSUE TITLE
asks for login everytime even with remember me checked 

### ISSUE THREAD

**Issue by prufaraSS** [rigormorrtiss/discordo#458]
here's what it tells: failed to get token from keyring err="The name is not activatable"
using two factor authentification
my specs: wayland, hyprland, no wlroots (aquamarine instead), kitty terminal, nvidia gpu (1050 ti), amd cpu, ssd (ext4), arch linux (linux-zen)

**Comment by ayn2op** [comment]
You need a keyring software that implements the DBus secret service API in order to securely store the authentication token. One such application is [`gnome-keyring`](https://wiki.archlinux.org/title/GNOME/Keyring).

**Comment by prufaraSS** [comment]
I've never heard anything about keyrings ever, so trying to make it work sent me to a medium-length rabbit hole. so what I've done to make things work:
1. Installed [gnome-keyring](https://archlinux.org/packages/extra/x86_64/gnome-keyring/)
2. Made sure [libsecret](https://archlinux.org/packages/core/x86_64/libsecret/) is installed
3. Setup default keyring password:
```
$ dbus-run-session -- sh
sh-5.2$ gnome-keyring-daemon --unlock
123 [Ctrl+D to exit]
sh-5.2$ exit
```
(Shoutout #413, [Using keyring on headless linux systems](https://github.com/jaraco/keyring/blob/main/README.rst#using-keyring-on-headless-linux-systems))
4. Setup system for using gnome keyrings:
`$ sudo nano /etc/pam.d/login`
```
#%PAM-1.0


auth       ...               ...
auth       optional     pam_gnome_keyring.so
account   ...             ...
session    ...            ...
session    optional     pam_gnome_keyring.so auto_start
```
(Basically saying to add _gnome keyring auth_ at the end of auth listings and _gnome keyring session_ below all session listings)
(Shoutout [Unable to log in - Arch Linux - Failed to store user ID to Keychain](https://forum.inkdrop.app/t/unable-to-log-in-arch-linux-failed-to-store-user-id-to-keychain/3045), [GNOME/Keyring: Using the keyring (PAM step) - ArchWiki](https://wiki.archlinux.org/title/GNOME/Keyring#Using_the_keyring))
5. Restarted the system and logged in discord account (Extra step: Closed Discordo and reopened it)

**Comment by prufaraSS** [comment]
For those who doesn't want to see a popup window of authentification every time discordo executed:
1. Make sure discordo automatically connects to your discord account on startup
2. Install [seahorse](https://archlinux.org/packages/extra/x86_64/seahorse/)
3. Open the program and find "Login" category: 
![image](https://github.com/user-attachments/assets/052943dc-2228-44b8-97cd-b442c00bf311)
4. Press right mouse button on it and select "Change Password"
5. Write your old password (on guide above used "123")
6. Press "Continue" every time until new popups appear
