### ISSUE TITLE
Any reason this doesn't use discordgo?

### ISSUE THREAD

**Issue by LukeW2002** [rigormorrtiss/discordo#460]
Title describes it all

**Comment by ayn2op** [comment]
Discordo used discordgo before, but discordgo officially ended support for user accounts after Discord started to remove libraries from [Libraries](https://discord.com/developers/docs/developer-tools/community-resources#libraries) section in the [Community Resources](https://discord.com/developers/docs/developer-tools/community-resources) page. Arikawa, on the other hand, officially supports user accounts and provides a pleasant API to do so. The author of Arikawa also maintains a GTK Discord client and uses ningen which is just a wrapper on top of Arikawa.
