### ISSUE TITLE
Guilds list got duplicated

### ISSUE THREAD

**Issue by prufaraSS** [rigormorrtiss/discordo#461]
For some reason Guilds list got duplicated. Maybe because this client was idle for like 4 hours or something, because when I tried to open different chat client did froze for like 10 seconds (which makes me think it was reconnecting to my account)

![image](https://github.com/user-attachments/assets/dbba04c1-b38f-42d9-892c-256a6ae49df2)

**Comment by ayn2op** [comment]
Duplicate: #403
