### ISSUE TITLE
2FA makes things weird

### ISSUE THREAD

**Issue by senorhamburgler** [rigormorrtiss/discordo#470]
When trying to login with a 2fa code on Zorin OS, discordo does nothing but all of my other clients on all other devices get logged out.

**Comment by Delta0001** [comment]
Same happened to me just now. Client just kinda froze up for a second and logged me out of all Discord sessions.

**Comment by SlightlyLargeProtogen** [comment]
same happened to me, but on Windows 10. scared the fuck out of me to see all my devices get logged out

**Comment by Ninty9** [comment]
Can confirm this happened also, i tried it again and the same thing happened

**Comment by robertjshirts** [comment]
Same thing here on Arch Linux, got logged out of mobile and desktop clients.

**Comment by ayn2op** [comment]
Duplicate: #465
