### ISSUE TITLE
 failed to get token from keyring: secret not found in keyring

### ISSUE THREAD

**Issue by tree-sapii** [rigormorrtiss/discordo#472]
I am on NixOS 24.05 with gnome keyring installed.
I have not put the secret inside the keyring nor is the keyring actually created.
When I run it without any args, I can enter my login normally but it errors with 
`2024/11/29 23:56:03 failed to get token from keyring: secret not found in keyring`

What can I do to fix this?

**Comment by RobinHirst11** [comment]
To fix this error, you need to add your Discord token to the GNOME keyring.

1. **Start the GNOME Keyring Daemon**:
   ```sh
   eval $(gnome-keyring-daemon --start)
   export $(gnome-keyring-daemon --start)
   ```

2. **Create a Keyring (if not created)**:
   ```sh
   seahorse
   ```
   In the Seahorse GUI, you can create a new keyring.

3. **Add the Secret to the Keyring**:
   ```sh
   secret-tool store --label='Discord Token' discord-token <YOUR_DISCORD_TOKEN>
   ```

**Comment by tree-sapii** [comment]
Yea, I did all of that.
I run the app, I still need to enter my email, password and 2FA.
Remember me is ticked on.
But when I click login it freezes :/

It only works when I provide my token as a command line argument.

**Comment by tree-sapii** [comment]
ok doing some debugging, it seems as the command needed is 
`secret-tool store --label="Discord Token" service discordo username token`

and when it prompts you for the password, you paste the token
