### ISSUE TITLE
Support for Discord-flavored markdown 

### ISSUE THREAD

**Issue by TheScreechingBagel** [rigormorrtiss/discordo#62]
seen this already in the readme, but thought an issue necessary for tracking purposes
bold, italics etc in accordance to https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

**Comment by TheScreechingBagel** [comment]
it should replace the special characters and hide them just like in the official client

**Comment by ghost** [comment]
Italic flag is not supported by tview yet. There is an [open PR](https://github.com/rivo/tview/pull/457) that implements the italic flag.

**Comment by TheScreechingBagel** [comment]
The PR has been opened for a while and i find it unlikely to be merged any time soon, as it is a low-priority feature in a low-priority project for the dev.
There is a fork, [cview](https://code.rocketnine.space/tslocum/cview), that implements PRs faster and seems to already have italics.

**Comment by ghost** [comment]
> The PR has been opened for a while and i find it unlikely to be merged any time soon, as it is a low-priority feature in a low-priority project for the dev. There is a fork, [cview](https://code.rocketnine.space/tslocum/cview), that implements PRs faster and seems to already have italics.

Looks like [cview](https://code.rocketnine.space/tslocum/cview) is missing the `TreeNode.GetLevel()` function which is required by Discordo. I can open a pull request on the `cview` repository, but I do not want to create a new account and they do not  support GitHub OAuth login.
