### ISSUE TITLE
Previously sent messages display in random order after selecting a channel

### ISSUE THREAD

**Issue by korvahkh** [rigormorrtiss/discordo#68]
After selecting a channel, messages that were previously sent display in a random order
![discordo2](https://user-images.githubusercontent.com/92224397/136668413-e85b94be-0e2b-4c3c-85bd-d6dee4f5f63c.png)
The problem is fixed by removing the `go` keyword in line 102 of ui.go:
```
func onChannelsTreeSelected(n *tview.TreeNode) {
...
	for i := len(ms) - 1; i >= 0; i-- {
		selectedChannel.Messages = append(selectedChannel.Messages, ms[i])
		go renderMessage(ms[i])
		//^ Right here
	}
...
}
```

**Comment by ghost** [comment]
The commit [`7cede44`](https://github.com/ayntgl/discordo/commit/7cede44f6008603819ea46cda04a9a543bd32989) should fix this issue. Feel free to reopen if the issue persists.
