### ISSUE TITLE
Feature request: Image support

### ISSUE THREAD

**Issue by jrvgr** [rigormorrtiss/discordo#95]
hi i would like to see image embeds being shown in the client itself instead of needing a external viewer for it

**Comment by B83C** [comment]
and also xclip image support

**Comment by im-viriv** [comment]
> and also xclip image support

this should be a seperate issue

**Comment by B83C** [comment]
and it would also be great to have support for xclip images

**Comment by DremOSDeveloperTeam** [comment]
Looking into this.

**Comment by TheScreechingBagel** [comment]
w3m ,the terminal browser does this:
https://github.com/tokuhirom/w3m/blob/master/w3mimg/x11/x11_w3mimg.c
edit: this is x11-only though...
and depends on xterm

**Comment by DremOSDeveloperTeam** [comment]
The implementation I attempted used SIXEL instead. Most terminals still don't support this standard, but actually printing the SIXEL escape sequences to the correct location and having it scroll does not seem easy, at least to me. The code that actually downloads and translates images to SIXEL escape sequences is done, and avalible in the "images" branch on my fork (after I push what I've pulled together tonight).

**Comment by TheScreechingBagel** [comment]
Here is a ranger issue #mentioning this:https://github.com/ranger/ranger/issues/1476
It mentions [imv](https://sr.ht/~exec64/imv/)

**Comment by KodiCraft** [comment]
A Kitty based implementation with something like [icat](https://sw.kovidgoyal.net/kitty/kittens/icat/) would be neat, but that would probably have to be implemented in a completely different way

**Comment by emilydaemon** [comment]
Being able to use chafa as the image backend would be nice.

**Comment by carterprince** [comment]
If this is implemented, it should definitely use [ueberzug](https://github.com/seebye/ueberzug) in my opinion. It would probably be complicated, though. For now, as a workaround, there should be a hotkey to open the link to an image in your preferred image viewer.

**Comment by ayntgl** [comment]
Discordo already uses `xdg-open` for Linux, `open` for OSX and `start` for Windows to open attachments in the default image viewer and links in the default browser.

**Comment by rihaq** [comment]
6cord had sixel support then why not discordo?

**Comment by diamondburned** [comment]
> 6cord had sixel support then why not discordo?

6cord actually did not have SIXEL support. As @DremOSDeveloperTeam pointed out, supporting SIXEL in something like tview is tedious work.

That said, [tcell-sixel](https://github.com/diamondburned/tcell-sixel) could be of use for that. [foot](https://codeberg.org/dnkl/foot) also supports SIXEL.

**Comment by peepo5** [comment]
@diamondburned it looks pretty good. Videos could also be implemented (but it would require some work haha)

**Comment by Cons-Cat** [comment]
Animated images that can move in a terminal efficiently is precisely what the Kitty graphics protocol was invented to do.

**Comment by rihaq** [comment]
> > 6cord had sixel support then why not discordo?
> 
> 6cord actually did not have SIXEL support. As @DremOSDeveloperTeam pointed out, supporting SIXEL in something like tview is tedious work.
> 
> That said, [tcell-sixel](https://github.com/diamondburned/tcell-sixel) could be of use for that. [foot](https://codeberg.org/dnkl/foot) also supports SIXEL.

Who told you? Then what is this? https://github.com/diamondburned/real6cord

**Comment by rihaq** [comment]
> Animated images that can move in a terminal efficiently is precisely what the Kitty graphics protocol was invented to do.

Fuck you why are you obsessed with kitty shitty ?

**Comment by Cons-Cat** [comment]
> > Animated images that can move in a terminal efficiently is precisely what the Kitty graphics protocol was invented to do.
> 
> Fuck you why are you obsessed with kitty shitty ?

Do you honestly think that Sixel is as good as Kitty's protocol?

**Comment by rihaq** [comment]
> > > Animated images that can move in a terminal efficiently is precisely what the Kitty graphics protocol was invented to do.
> > 
> > 
> > Fuck you why are you obsessed with kitty shitty ?
> 
> Do you honestly think that Sixel is as good as Kitty's protocol?

Nope, I don't think sixel is good




















**SIXEL IS BEST**

**Comment by rihaq** [comment]
> > > Animated images that can move in a terminal efficiently is precisely what the Kitty graphics protocol was invented to do.
> > 
> > 
> > Fuck you why are you obsessed with kitty shitty ?
> 
> Do you honestly think that Sixel is as good as Kitty's protocol?

You need a dose of copium

**Comment by diamondburned** [comment]
> Who told you? Then what is this? https://github.com/diamondburned/real6cord

It's garbage that does not work :upside_down_face: 

Try asking the developer and see what they have to say about it.

P/S: I'm not going to babysit this issue (it's not my issue), but I would much rather we maintain a constructive tone rather than yelling "dose of copium" at someone else. I don't think that's at all productive or helpful to anyone.

**Comment by ayn2op** [comment]
https://github.com/rivo/tview/wiki/Image
